//! Hand-written C-ABI bridge for the `regex` crate (M0 baseline reference).
//!
//! This is the hand-authored version that M2 (`#[jac_bridge::bridge]`) was built
//! to match.  See jac-bridge-regex-v2 for the macro-generated equivalent.
//! Every shim is `catch_unwind`-guarded so Rust panics never unwind into the host.
//!
//! ABI conventions (D2):
//!   - Strings cross as (ptr: *const u8, len: u32) — no NUL termination.
//!   - Fallible fns return i32 status (0=ok, 1=err, 2=panic) plus out-params.
//!   - Opaque handles are Box<T> cast to u64; 0 is always invalid.
//!   - Heap-allocated return strings come back as JacBuf; freed by jac_regex_free_buf.
//!   - All shims are module-prefixed (jac_regex_*) to avoid symbol collisions
//!     when a program imports multiple bridges.

#![allow(clippy::missing_safety_doc)]

// Generated by build.rs: META_LEN (usize) + META_DATA ([u8; META_LEN])
include!(concat!(env!("OUT_DIR"), "/meta.rs"));

use std::panic::AssertUnwindSafe;

// ---- Status codes -----------------------------------------------------------

const STATUS_OK: i32 = 0;
const STATUS_ERR: i32 = 1;
const STATUS_PANIC: i32 = 2;

// ---- ABI types --------------------------------------------------------------

/// A heap buffer owned by this bridge library.
/// The caller must free it with `jac_regex_free_buf`; no other allocator may free it.
#[repr(C)]
pub struct JacBuf {
    pub ptr: *mut u8,
    pub len: u32,
    pub cap: u32,
}

// ---- D3: Send assertion ----------------------------------------------------
// Every opaque type crossing the boundary must be Send (required by the RC
// machinery which can drop from any thread).  This is a compile-time check.
const _: () = {
    fn _assert_send<T: Send>() {}
    fn _check() {
        _assert_send::<regex::Regex>();
    }
};

// ---- D2: Metadata section static -------------------------------------------
//
// The blob produced by build.rs is placed in a named ELF/Mach-O/PE section so
// a cross-compiling host can parse it from the binary without dlopen.
// `jac_bridge_init_regex` returns its address; that live reference prevents the
// linker from GC-ing the section even with --gc-sections.

#[used]
#[cfg_attr(target_os = "linux",  link_section = ".jac_bridge")]
#[cfg_attr(target_os = "macos",  link_section = "__DATA,__jac_bridge")]
#[cfg_attr(windows,              link_section = ".jacbrdg")]
static JAC_BRIDGE_META: [u8; META_LEN] = META_DATA;

/// Return the address of the metadata blob.
/// The loader reads blob_len at offset 16 to know how many bytes to consume.
#[no_mangle]
pub extern "C" fn jac_bridge_init_regex() -> *const u8 {
    JAC_BRIDGE_META.as_ptr()
}

// ---- Internal helpers -------------------------------------------------------

fn string_to_jacbuf(s: String) -> JacBuf {
    let mut v = s.into_bytes();
    let ptr = v.as_mut_ptr();
    let len = v.len() as u32;
    let cap = v.capacity() as u32;
    std::mem::forget(v);
    JacBuf { ptr, len, cap }
}

fn panic_err_handle(msg: &str) -> u64 {
    Box::into_raw(Box::new(msg.to_string())) as u64
}

// ---- Shims ------------------------------------------------------------------

/// Compile `pattern` into a `Regex` handle.
///
/// On success: `*out_handle` = handle, `*out_err` = 0, returns STATUS_OK.
/// On regex error: `*out_handle` = 0, `*out_err` = RegexError handle, returns STATUS_ERR.
/// On panic: same shape as err, returns STATUS_PANIC.
#[no_mangle]
pub unsafe extern "C" fn jac_regex_Regex_new(
    pattern_ptr: *const u8,
    pattern_len: u32,
    out_handle: *mut u64,
    out_err: *mut u64,
) -> i32 {
    let r = std::panic::catch_unwind(AssertUnwindSafe(|| {
        let bytes = std::slice::from_raw_parts(pattern_ptr, pattern_len as usize);
        let pat = std::str::from_utf8(bytes).map_err(|e| format!("UTF-8: {e}"))?;
        regex::Regex::new(pat).map_err(|e| e.to_string())
    }));
    match r {
        Ok(Ok(re)) => {
            *out_handle = Box::into_raw(Box::new(re)) as u64;
            *out_err = 0;
            STATUS_OK
        }
        Ok(Err(msg)) => {
            *out_handle = 0;
            *out_err = Box::into_raw(Box::new(msg)) as u64;
            STATUS_ERR
        }
        Err(_) => {
            *out_handle = 0;
            *out_err = panic_err_handle("panic in jac_regex_Regex_new");
            STATUS_PANIC
        }
    }
}

/// Test whether `handle` matches `text`.
///
/// On success: `*out_bool` = 0 or 1, `*out_err` = 0, returns STATUS_OK.
/// The `out_err` / STATUS_ERR arm fires only on invalid-UTF-8 text.
/// STATUS_PANIC fires if the regex engine panics.
#[no_mangle]
pub unsafe extern "C" fn jac_regex_Regex_is_match(
    handle: u64,
    text_ptr: *const u8,
    text_len: u32,
    out_bool: *mut u8,
    out_err: *mut u64,
) -> i32 {
    let r = std::panic::catch_unwind(AssertUnwindSafe(|| {
        let re = &*(handle as *const regex::Regex);
        let bytes = std::slice::from_raw_parts(text_ptr, text_len as usize);
        let text = std::str::from_utf8(bytes).map_err(|e| format!("UTF-8: {e}"))?;
        Ok::<bool, String>(re.is_match(text))
    }));
    match r {
        Ok(Ok(b)) => {
            *out_bool = b as u8;
            *out_err = 0;
            STATUS_OK
        }
        Ok(Err(msg)) => {
            *out_bool = 0;
            *out_err = Box::into_raw(Box::new(msg)) as u64;
            STATUS_ERR
        }
        Err(_) => {
            *out_bool = 0;
            *out_err = panic_err_handle("panic in jac_regex_Regex_is_match");
            STATUS_PANIC
        }
    }
}

/// Release a Regex handle.  Called automatically by the dtor synthesized into
/// each Jac object's header; also usable as an explicit `close()`.
/// Idempotent on 0.
#[no_mangle]
pub unsafe extern "C" fn jac_regex_Regex_drop(handle: u64) {
    if handle != 0 {
        drop(Box::from_raw(handle as *mut regex::Regex));
    }
}

/// Copy the message from a RegexError handle into a new JacBuf.
/// The caller owns the returned JacBuf and must free it with `jac_regex_free_buf`.
/// Infallible assuming `err_handle` is valid; STATUS_PANIC if the impl panics.
#[no_mangle]
pub unsafe extern "C" fn jac_regex_error_message(
    err_handle: u64,
    out_buf: *mut JacBuf,
    out_err: *mut u64,
) -> i32 {
    let r = std::panic::catch_unwind(AssertUnwindSafe(|| {
        let msg = &*(err_handle as *const String);
        string_to_jacbuf(msg.clone())
    }));
    match r {
        Ok(buf) => {
            *out_buf = buf;
            *out_err = 0;
            STATUS_OK
        }
        Err(_) => {
            *out_buf = JacBuf { ptr: std::ptr::null_mut(), len: 0, cap: 0 };
            *out_err = panic_err_handle("panic in jac_regex_error_message");
            STATUS_PANIC
        }
    }
}

/// Release a RegexError handle.  Idempotent on 0.
#[no_mangle]
pub unsafe extern "C" fn jac_regex_error_drop(err_handle: u64) {
    if err_handle != 0 {
        drop(Box::from_raw(err_handle as *mut String));
    }
}

/// Free a JacBuf allocated by this library.
/// Allocators must never mix: only call this on buffers returned by this bridge.
#[no_mangle]
pub unsafe extern "C" fn jac_regex_free_buf(buf: JacBuf) {
    if !buf.ptr.is_null() {
        drop(Vec::from_raw_parts(buf.ptr, buf.len as usize, buf.cap as usize));
    }
}

// ---- Tests ------------------------------------------------------------------
//
// These cover the exact failure modes called out in M0:
//   - ptr+len strings, never NUL-terminated
//   - handle round-trip
//   - drop called exactly once (handle=0 is a safe no-op)
//   - Result::Err → error handle with message
//   - Rust panic → STATUS_PANIC + readable error handle
//   - JacBuf ownership (alloc here, free here)
//   - Section metadata parseable as bytes (no dlopen)

#[cfg(test)]
mod tests {
    use super::*;
    use std::mem::MaybeUninit;

    // ---- helpers ------------------------------------------------------------

    unsafe fn compile(pattern: &str) -> u64 {
        let mut h = 0u64;
        let mut e = 0u64;
        let st = jac_regex_Regex_new(pattern.as_ptr(), pattern.len() as u32, &mut h, &mut e);
        assert_eq!(st, STATUS_OK, "unexpected compile failure");
        assert_ne!(h, 0);
        assert_eq!(e, 0);
        h
    }

    unsafe fn is_match(handle: u64, text: &str) -> bool {
        let mut b = 0u8;
        let mut e = 0u64;
        let st = jac_regex_Regex_is_match(
            handle, text.as_ptr(), text.len() as u32, &mut b, &mut e,
        );
        assert_eq!(st, STATUS_OK);
        assert_eq!(e, 0);
        b != 0
    }

    // ---- handle round-trip --------------------------------------------------

    #[test]
    fn test_match_and_no_match() {
        unsafe {
            let h = compile(r"foo\d+");
            assert!(is_match(h, "foo42"));
            assert!(!is_match(h, "bar99"));
            jac_regex_Regex_drop(h);
        }
    }

    // ---- ptr+len strings: no NUL reliance -----------------------------------

    #[test]
    fn test_ptr_len_no_nul_reliance() {
        // Pattern "hello\0extra" — only the first 5 bytes should be compiled.
        // Text "hello\0world" — only first 5 bytes matched.
        unsafe {
            let raw = b"hello\x00extra";
            let mut h = 0u64;
            let mut e = 0u64;
            let st = jac_regex_Regex_new(raw.as_ptr(), 5, &mut h, &mut e);
            assert_eq!(st, STATUS_OK, "NUL in subsequent bytes must not affect compile");

            let text = b"hello\x00world";
            let mut b = 0u8;
            let mut be = 0u64;
            let st2 = jac_regex_Regex_is_match(h, text.as_ptr(), 5, &mut b, &mut be);
            assert_eq!(st2, STATUS_OK);
            assert_eq!(b, 1, "should match the first 5 bytes only");
            jac_regex_Regex_drop(h);
        }
    }

    // ---- drop exactly once --------------------------------------------------

    #[test]
    fn test_drop_zero_is_noop() {
        // Must not crash or access invalid memory.
        unsafe { jac_regex_Regex_drop(0) };
        unsafe { jac_regex_error_drop(0) };
    }

    #[test]
    fn test_explicit_close_then_zero_drop() {
        // Simulates: explicit close() followed by RC-death calling the dtor with handle=0.
        unsafe {
            let h = compile("abc");
            jac_regex_Regex_drop(h);
            jac_regex_Regex_drop(0); // safe no-op after an explicit close zeroed the field
        }
    }

    // ---- Result::Err → error handle with message ----------------------------

    #[test]
    fn test_invalid_pattern_returns_error_handle() {
        unsafe {
            let pat = b"(unclosed";
            let mut h = 0u64;
            let mut e = 0u64;
            let st = jac_regex_Regex_new(pat.as_ptr(), pat.len() as u32, &mut h, &mut e);
            assert_eq!(st, STATUS_ERR);
            assert_eq!(h, 0);
            assert_ne!(e, 0, "error handle must be non-zero");

            // Read the message via JacBuf.
            let mut buf = MaybeUninit::<JacBuf>::uninit();
            let mut be = 0u64;
            let bst = jac_regex_error_message(e, buf.as_mut_ptr(), &mut be);
            assert_eq!(bst, STATUS_OK);
            let buf = buf.assume_init();
            assert!(buf.len > 0, "error message must be non-empty");
            let msg = std::str::from_utf8(
                std::slice::from_raw_parts(buf.ptr, buf.len as usize)
            ).unwrap();
            assert!(!msg.is_empty());

            // Ownership: free the JacBuf, then free the error handle.
            jac_regex_free_buf(buf);
            jac_regex_error_drop(e);
        }
    }

    // ---- JacBuf ownership ---------------------------------------------------

    #[test]
    fn test_free_buf_without_double_free() {
        // Compile a bad pattern, get the error message into a JacBuf, free it.
        // If there were a double-free or use-after-free this would corrupt the heap.
        unsafe {
            let pat = b"[bad";
            let mut h = 0u64;
            let mut e = 0u64;
            jac_regex_Regex_new(pat.as_ptr(), pat.len() as u32, &mut h, &mut e);
            assert_ne!(e, 0);

            let mut buf1 = MaybeUninit::<JacBuf>::uninit();
            let mut be = 0u64;
            jac_regex_error_message(e, buf1.as_mut_ptr(), &mut be);
            let buf1 = buf1.assume_init();

            // A second call clones the string into a fresh JacBuf.
            let mut buf2 = MaybeUninit::<JacBuf>::uninit();
            jac_regex_error_message(e, buf2.as_mut_ptr(), &mut be);
            let buf2 = buf2.assume_init();

            // The two JacBufs are independent allocations; both must be freed.
            jac_regex_free_buf(buf1);
            jac_regex_free_buf(buf2);
            jac_regex_error_drop(e);
        }
    }

    // ---- Section metadata: parse as bytes, no dlopen -----------------------
    //
    // This is the "cross-compile simulation": we read the section static directly
    // as bytes, exactly as the M3 na compiler will do when it parses the ELF section
    // from disk without executing the library.

    // The committed reference vector (M1): this hand-written blob IS the reference
    // every other producer must reproduce. Guards the golden file against drift in
    // the hand-written crate; jac-bridge-regex-v2 asserts the macro reproduces it.
    #[test]
    fn test_blob_matches_reference_vector() {
        let reference = include_bytes!("../../reference/regex.jacbridge");
        assert_eq!(
            &JAC_BRIDGE_META[..], &reference[..],
            "hand-written blob diverged from reference/regex.jacbridge — \
             if intentional, regenerate the vector (see reference/README.md)"
        );
    }

    #[test]
    fn test_metadata_magic() {
        let blob = &JAC_BRIDGE_META;
        assert_eq!(&blob[0..8], b"JACBRDG1", "wrong magic");
    }

    #[test]
    fn test_metadata_abi_version() {
        let blob = &JAC_BRIDGE_META;
        let v = u32::from_le_bytes(blob[8..12].try_into().unwrap());
        assert_eq!(v, 1);
    }

    #[test]
    fn test_metadata_blob_len() {
        let blob = &JAC_BRIDGE_META;
        let reported = u32::from_le_bytes(blob[16..20].try_into().unwrap()) as usize;
        assert_eq!(reported, blob.len(), "blob_len must match actual size");
    }

    #[test]
    fn test_metadata_type_and_fn_counts() {
        let blob = &JAC_BRIDGE_META;
        let types_count = u32::from_le_bytes(blob[44..48].try_into().unwrap());
        let fns_count   = u32::from_le_bytes(blob[52..56].try_into().unwrap());
        assert_eq!(types_count, 2, "expected Regex + RegexError");
        assert_eq!(fns_count, 3, "expected new + is_match + message");
    }

    #[test]
    fn test_metadata_module_name() {
        let blob = &JAC_BRIDGE_META;
        let off = u32::from_le_bytes(blob[24..28].try_into().unwrap()) as usize;
        let len = u32::from_le_bytes(blob[28..32].try_into().unwrap()) as usize;
        let name = std::str::from_utf8(&blob[off..off + len]).unwrap();
        assert_eq!(name, "regex");
    }

    #[test]
    fn test_metadata_type0_name_and_drop_symbol() {
        let blob = &JAC_BRIDGE_META;
        // TypeDesc[0] at offset 56
        let td0 = 56usize;
        let name_off = u32::from_le_bytes(blob[td0+8 ..td0+12].try_into().unwrap()) as usize;
        let name_len = u32::from_le_bytes(blob[td0+12..td0+16].try_into().unwrap()) as usize;
        let drop_off = u32::from_le_bytes(blob[td0+16..td0+20].try_into().unwrap()) as usize;
        let drop_len = u32::from_le_bytes(blob[td0+20..td0+24].try_into().unwrap()) as usize;
        assert_eq!(std::str::from_utf8(&blob[name_off..name_off+name_len]).unwrap(), "Regex");
        assert_eq!(std::str::from_utf8(&blob[drop_off..drop_off+drop_len]).unwrap(), "jac_regex_Regex_drop");
    }

    #[test]
    fn test_metadata_fn0_symbol_and_ret() {
        let blob = &JAC_BRIDGE_META;
        // FnDesc[0] at offset 120
        let fd0 = 120usize;
        // symbol StrRef at fd0+12
        let sym_off = u32::from_le_bytes(blob[fd0+12..fd0+16].try_into().unwrap()) as usize;
        let sym_len = u32::from_le_bytes(blob[fd0+16..fd0+20].try_into().unwrap()) as usize;
        assert_eq!(std::str::from_utf8(&blob[sym_off..sym_off+sym_len]).unwrap(), "jac_regex_Regex_new");
        // ret TypeTag at fd0+32 — should be TYPE_REF(0) = 0x8000_0000
        let ret = u32::from_le_bytes(blob[fd0+32..fd0+36].try_into().unwrap());
        assert_eq!(ret, 0x8000_0000u32, "ret should be TYPE_REF(0) = Regex");
    }

    #[test]
    fn test_init_returns_metadata_ptr() {
        let ptr = jac_bridge_init_regex();
        assert!(!ptr.is_null());
        let slice = unsafe { std::slice::from_raw_parts(ptr, 8) };
        assert_eq!(slice, b"JACBRDG1");
    }
}
