- id: jac-format
  name: jac-format
  description: Format Jac files with consistent code style
  entry: python3 jac/jaclang/compiler/__init__.py; jac format
  language: python
  types: [file]
  files: \.jac$
  require_serial: true

- id: jac-check
  name: jac-check
  description: Type check Jac files
  entry: python3 jac/jaclang/compiler/__init__.py; jac check
  language: python
  types: [file]
  files: \.jac$
  require_serial: true
