[project]
name = "react-flow-template"
version = "1.0.0"
description = "Jac client application: react-flow-template"
entry-point = "main.jac"

[dependencies.npm]
jac-client-node = "1.0.3"
reactflow = "latest"
"@xyflow/react" = "latest"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client]
