[project]
name = "byllm"
version = "0.5.5"
description = "byLLM Provides Easy to use APIs for different LLM Providers to be used with Jaseci's Jaclang Programming Language."
entry-point = "byllm/plugin.jac"
readme = "README.md"
license = "MIT"
jac-version = ">=0.10.0"
authors = ["Jason Mars <jason@mars.ninja>"]
keywords = ["llm", "jaclang", "jaseci", "byLLM"]

[project.urls]
homepage = "https://github.com/Jaseci-Labs/jaseci"
repository = "https://github.com/Jaseci-Labs/jaseci"
documentation = "https://jaseci.org"

[project.entry-points.jac]
byllm = "byllm.plugin:JacRuntime"
byllm_plugin_config = "byllm.plugin_config:JacByllmPluginConfig"

[dependencies]
jaclang = ">=0.10.0"
litellm = ">=1.75.5.post1,<1.80.0"
loguru = ">=0.7.2,<0.8.0"
pillow = ">=10.4.0,<10.5.0"

[dev-dependencies]
pytest = ">=8.3.2"

[optional-dependencies.tools]
wikipedia = ">=0.0.0"

[optional-dependencies.video]
opencv-python-headless = ">=0.0.0"

[build]
typecheck = false
dir = ".jac"

[scripts]
test = "jac test"
build = "jac build byllm/plugin.jac"

[plugins]
discovery = "auto"
