use std::fmt::Write;

use crate::types::{
    BridgeFn, BridgeReturn, BridgeSpec, BridgeType, OwningWrapper, Recv, ScalarType, TypeKind,
};

/// Emit a `Cargo.toml` for the generated bridge crate.
///
/// `jac_bridge_path` is a path (relative or absolute) to the `jac-bridge`
/// crate directory, written verbatim into the `[dependencies]` table.
pub fn emit_cargo_toml(spec: &BridgeSpec, jac_bridge_path: &str) -> String {
    format!(
        r#"# Auto-generated by jac-bridge-binder. Do not edit.
[package]
name = "jac-bridge-{module}"
version = "0.1.0"
edition = "2021"
description = "Auto-generated bridge for {module} {crate_version}"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jac-bridge = {{ path = "{jac_bridge_path}" }}
{module} = "={crate_version}"
"#,
        module = spec.module_name,
        crate_version = spec.crate_version,
        jac_bridge_path = jac_bridge_path,
    )
}

/// Emit a `#[bridge(module = "...")]` Rust source file from a `BridgeSpec`.
///
/// The output is a valid `src/lib.rs` for a bridge crate that depends on
/// `jac_bridge` and the bridged crate.  It mirrors the structure of
/// `jac-bridge-regex-v2/src/lib.rs` but is generated rather than hand-written.
pub fn emit(spec: &BridgeSpec) -> String {
    let mut out = String::new();

    writeln!(out, "// Auto-generated by jac-bridge-binder. Do not edit.").unwrap();
    writeln!(out, "// crate: {}  version: {}", spec.module_name, spec.crate_version).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use jac_bridge::bridge;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[bridge(module = \"{}\")]", spec.module_name).unwrap();
    // Generated code: a bridged type whose full surface isn't yet covered can
    // have a ctor but no reading method (field written, never read). The macro
    // preserves module attrs, so this silences dead_code across the bridge.
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "mod bridge_impl {{").unwrap();

    // ── struct declarations ───────────────────────────────────────────────────

    let mut first = true;
    for bt in &spec.types {
        // An opaque type with no ctor, no methods, and no injected source can
        // never be constructed or called through the bridge — emitting it is
        // dead weight (a drop shim for an unreachable handle) and trips
        // `dead_code`. Skip it so generated crates compile warning-clean.
        if is_dead_opaque(bt) {
            continue;
        }
        if !first {
            writeln!(out).unwrap();
        }
        first = false;

        match bt.kind {
            TypeKind::Opaque if bt.wrapper.is_some() => {
                emit_wrapper_struct(&mut out, bt, bt.wrapper.as_ref().unwrap());
            }
            TypeKind::Opaque => {
                writeln!(out, "    pub struct {}(pub {});", bt.name, bt.inner_path).unwrap();
            }
            TypeKind::Error => {
                let bname = error_bridge_name(&bt.name, &spec.module_name);
                writeln!(out, "    #[jac_error]").unwrap();
                writeln!(out, "    pub struct {};", bname).unwrap();
            }
        }
    }

    // ── impl blocks ───────────────────────────────────────────────────────────

    for bt in &spec.types {
        if bt.kind == TypeKind::Error {
            continue;
        }

        // Synthesized wrappers get a non-pub `wrap` constructor (the ouroboros
        // lifetime-erasure) emitted before their readers.
        let wrap_src = bt.wrapper.as_ref().map(|w| emit_wrap(w, bt));
        let ctor_src = bt.ctor.as_ref().and_then(|f| emit_fn(f, bt, true));
        let method_srcs: Vec<String> =
            bt.methods.iter().filter_map(|f| emit_fn(f, bt, false)).collect();

        if wrap_src.is_none()
            && ctor_src.is_none()
            && method_srcs.is_empty()
            && bt.injected_source.is_empty()
        {
            continue;
        }

        writeln!(out).unwrap();
        writeln!(out, "    impl {} {{", bt.name).unwrap();

        let mut first_fn = true;
        for src in wrap_src.into_iter().chain(ctor_src).chain(method_srcs) {
            if !first_fn {
                writeln!(out).unwrap();
            }
            writeln!(out, "{}", src).unwrap();
            first_fn = false;
        }
        for raw in &bt.injected_source {
            if !first_fn {
                writeln!(out).unwrap();
            }
            // raw snippets are written verbatim — overlay author is responsible for indentation
            write!(out, "{}", raw).unwrap();
            first_fn = false;
        }

        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}").unwrap();
    out
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// True for an opaque type with no bridgeable surface at all — nothing
/// constructs it and no method touches it, so it must not be emitted.
fn is_dead_opaque(bt: &BridgeType) -> bool {
    bt.kind == TypeKind::Opaque
        && bt.ctor.is_none()
        && bt.methods.is_empty()
        && bt.injected_source.is_empty()
}

/// Error types whose source name is just `"Error"` are renamed to
/// `<Module>Error` so the bridge module has a distinct, namespaced identifier.
fn error_bridge_name(name: &str, module_name: &str) -> String {
    if name == "Error" {
        let mut cap = module_name.to_string();
        if let Some(first) = cap.get_mut(0..1) {
            first.make_ascii_uppercase();
        }
        format!("{}Error", cap)
    } else {
        name.to_string()
    }
}

/// `<'static>` (or `<'static, 'static>`, …) for an `n`-lifetime borrowed type.
fn static_args(n: usize) -> String {
    if n == 0 {
        return String::new();
    }
    let lts = vec!["'static"; n].join(", ");
    format!("<{lts}>")
}

/// Emit the ouroboros struct for a synthesized owning wrapper: the borrowing
/// value (lifetime erased to `'static`) declared before the owned input it
/// points into, so it drops first.
fn emit_wrapper_struct(out: &mut String, bt: &BridgeType, w: &OwningWrapper) {
    writeln!(out, "    pub struct {} {{", bt.name).unwrap();
    writeln!(
        out,
        "        inner: {}{},",
        w.borrowed_path,
        static_args(w.lifetimes)
    )
    .unwrap();
    writeln!(out, "        _input: String,").unwrap();
    writeln!(out, "    }}").unwrap();
}

/// Emit the non-pub `wrap` constructor: clone the input, produce the borrowed
/// value from it, erase the lifetime, and store both.
fn emit_wrap(w: &OwningWrapper, bt: &BridgeType) -> String {
    let static_ty = format!("{}{}", w.borrowed_path, static_args(w.lifetimes));
    format!(
        "        fn wrap(owner: &{owner}, input: &str) -> Option<{wname}> {{\n\
         \x20           let owned = input.to_owned();\n\
         \x20           let inner = owner.{producer}(&owned)?;\n\
         \x20           // SAFETY: `inner` borrows `owned`, which is moved into the returned\n\
         \x20           // struct beside it and never mutated or moved-out; the borrower drops\n\
         \x20           // before the owner. Erasing to 'static is sound for the value's life.\n\
         \x20           let inner: {static_ty} = unsafe {{ std::mem::transmute(inner) }};\n\
         \x20           Some({wname} {{ inner, _input: owned }})\n\
         \x20       }}",
        owner = w.owner_inner_path,
        wname = bt.name,
        producer = w.producer_call,
    )
}

/// Render one function (constructor or method) as indented bridge source.
///
/// `classify` only admits params `ScalarType` can represent (`&str`, `bool`);
/// anything else is already a recorded skip, so this always emits.
fn emit_fn(f: &BridgeFn, bt: &BridgeType, is_ctor: bool) -> Option<String> {
    // Signature param list.
    let mut sig_parts: Vec<String> = Vec::new();
    if !is_ctor {
        sig_parts.push("&self".into());
    }
    for p in &f.params {
        let ty = match p.ty {
            ScalarType::Str => "&str",
            ScalarType::Bool => "bool",
        };
        sig_parts.push(format!("{}: {}", p.name, ty));
    }
    let params_str = sig_parts.join(", ");
    let args_str =
        f.params.iter().map(|p| p.name.as_str()).collect::<Vec<_>>().join(", ");

    let inner = &bt.inner_path;
    // `fname` is the Rust call target; the emitted `pub fn` uses the exposed
    // (possibly overlay-renamed) name so the Jac side sees the nicer identifier.
    let fname = &f.name;
    let exposed = f.exposed();
    // Receiver a method body delegates through: the newtype field for ordinary
    // methods, the erased borrowing value for a synthesized wrapper's readers.
    let recv = match f.recv {
        Recv::Field0 => "self.0",
        Recv::Inner => "self.inner",
    };

    let (ret_ann, body): (String, String) = match &f.ret {
        BridgeReturn::Void => {
            let call = if is_ctor {
                format!("{}::{}({})", inner, fname, args_str)
            } else {
                format!("{}.{}({})", recv, fname, args_str)
            };
            (String::new(), call)
        }
        BridgeReturn::Bool => {
            let call = if is_ctor {
                format!("{}::{}({})", inner, fname, args_str)
            } else {
                format!("{}.{}({})", recv, fname, args_str)
            };
            (" -> bool".into(), call)
        }
        BridgeReturn::Str => {
            // Bridge macro expects `String` (not `&str`) so convert via to_string().
            let call = if is_ctor {
                format!("{}::{}({}).to_string()", inner, fname, args_str)
            } else {
                format!("{}.{}({}).to_string()", recv, fname, args_str)
            };
            (" -> String".into(), call)
        }
        BridgeReturn::OwnSelf => {
            let call = if is_ctor {
                format!("Self({}::{}({}))", inner, fname, args_str)
            } else {
                format!("Self({}.{}({}))", recv, fname, args_str)
            };
            (" -> Self".into(), call)
        }
        BridgeReturn::OwnSelfResult => {
            let call = if is_ctor {
                format!(
                    "{}::{}({}).map(Self).map_err(|e| e.to_string())",
                    inner, fname, args_str
                )
            } else {
                format!(
                    "{}.{}({}).map(Self).map_err(|e| e.to_string())",
                    recv, fname, args_str
                )
            };
            (" -> Result<Self, String>".into(), call)
        }
        BridgeReturn::OptWrapper(wrapper) => {
            // Producer of an owning wrapper: delegate to the wrapper's `wrap`
            // ctor, which owns the input and erases the borrow. Always a method.
            let call = format!("{}::wrap(&self.0, {})", wrapper, args_str);
            (format!(" -> Option<{}>", wrapper), call)
        }
    };

    Some(format!(
        "        pub fn {}({}){} {{\n            {}\n        }}",
        exposed, params_str, ret_ann, body
    ))
}
