use std::fmt::Write;

use crate::types::{
    BridgeFn, BridgeReturn, BridgeSpec, BridgeType, DrainCollect, Ownership, OwningWrapper, Recv,
    RootProducer, ScalarType, TypeKind, WrapperKind,
};

/// Emit a `Cargo.toml` for the generated bridge crate.
///
/// `jac_bridge_path` is a path (relative or absolute) to the `jac-bridge`
/// crate directory, written verbatim into the `[dependencies]` table.
pub fn emit_cargo_toml(spec: &BridgeSpec, jac_bridge_path: &str) -> String {
    let has_async = spec_has_async(spec);
    let tokio_dep = if has_async {
        "tokio = { version = \"1\", features = [\"rt-multi-thread\", \"time\", \"net\"] }\n"
    } else {
        ""
    };
    // Source-crate dependency line. Features from the overlay `[crate] features`
    // (2.4) MUST land here or the optional serde impls the wide lane depends on
    // are compiled out of the bridge, even though rustdoc documented them. A
    // bare `= "=x"` stays bare so default-feature bridges are byte-identical.
    let crate_dep = if spec.crate_features.is_empty() {
        format!("{} = \"={}\"", spec.module_name, spec.crate_version)
    } else {
        let feats = spec
            .crate_features
            .iter()
            .map(|f| format!("\"{f}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "{} = {{ version = \"={}\", features = [{}] }}",
            spec.module_name, spec.crate_version, feats
        )
    };
    // Track A (1.1.5) needs NO extra dependency: a flattened trait is `use`d through
    // the bridged crate's own re-export (`sha2::Digest`), so the crate already in
    // `[dependencies]` supplies it at the exact version it uses. See
    // `Ctx::trait_use_path`.
    format!(
        r#"# Auto-generated by jac-bridge-binder. Do not edit.
[package]
name = "jac-bridge-{module}"
version = "0.1.0"
edition = "2021"
description = "Auto-generated bridge for {module} {crate_version}"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jac-bridge = {{ path = "{jac_bridge_path}" }}
{crate_dep}
{tokio_dep}"#,
        module = spec.module_name,
        crate_version = spec.crate_version,
        jac_bridge_path = jac_bridge_path,
        crate_dep = crate_dep,
        tokio_dep = tokio_dep,
    )
}

fn spec_has_async(spec: &BridgeSpec) -> bool {
    spec.types.iter().any(|bt| {
        bt.ctor
            .iter()
            .chain(bt.methods.iter())
            .any(|f| f.is_async)
    })
}

/// Distinct fully-qualified trait paths flattened onto any emitted fn (Track A,
/// 1.1.4/1.1.5). A flattened method delegates through `self.0.<name>(…)`, whose
/// resolution needs the trait in scope, so each path becomes a `use` inside the
/// generated module (and, when its crate root differs from the bridged module, a
/// dependency in the generated Cargo.toml). Sorted + deduped for deterministic,
/// warning-clean output.
fn flattened_trait_paths(spec: &BridgeSpec) -> Vec<String> {
    let mut paths: Vec<String> = spec
        .types
        .iter()
        .flat_map(|bt| bt.ctor.iter().chain(bt.methods.iter()))
        .filter_map(|f| f.via_trait.clone())
        .collect();
    paths.sort();
    paths.dedup();
    paths
}

/// Emit a `#[bridge(module = "...")]` Rust source file from a `BridgeSpec`.
///
/// The output is a valid `src/lib.rs` for a bridge crate that depends on
/// `jac_bridge` and the bridged crate.  It mirrors the structure of
/// `jac-bridge-regex-v2/src/lib.rs` but is generated rather than hand-written.
pub fn emit(spec: &BridgeSpec) -> String {
    let mut out = String::new();

    writeln!(out, "// Auto-generated by jac-bridge-binder. Do not edit.").unwrap();
    writeln!(
        out,
        "// crate: {}  version: {}",
        spec.module_name, spec.crate_version
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use jac_bridge::bridge;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[bridge(module = \"{}\")]", spec.module_name).unwrap();
    // Generated code: a bridged type whose full surface isn't yet covered can
    // have a ctor but no reading method (field written, never read). The macro
    // preserves module attrs, so this silences dead_code across the bridge.
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "mod bridge_impl {{").unwrap();

    // A HashMap<String, V> return re-declares the `HashMap` type in the wrapper
    // signature, so bring it into scope (Vec is in the prelude).
    if spec_has_map_return(spec) {
        writeln!(out, "    use std::collections::HashMap;").unwrap();
        writeln!(out).unwrap();
    }

    // Track A: bring every flattened trait into scope so the delegating call
    // `self.0.<method>()` resolves to the trait method (`use chrono::Datelike;`).
    let trait_uses = flattened_trait_paths(spec);
    if !trait_uses.is_empty() {
        for tp in &trait_uses {
            writeln!(out, "    use {tp};").unwrap();
        }
        writeln!(out).unwrap();
    }

    // ── struct declarations ───────────────────────────────────────────────────

    let mut first = true;
    for bt in &spec.types {
        // An opaque type with no ctor, no methods, and no injected source can
        // never be constructed or called through the bridge — emitting it is
        // dead weight (a drop shim for an unreachable handle) and trips
        // `dead_code`. Skip it so generated crates compile warning-clean.
        if is_dead_opaque(bt) {
            continue;
        }
        if !first {
            writeln!(out).unwrap();
        }
        first = false;

        match bt.kind {
            TypeKind::Opaque if bt.wrapper.is_some() => {
                emit_wrapper_struct(&mut out, bt, bt.wrapper.as_ref().unwrap());
            }
            TypeKind::Opaque => {
                writeln!(out, "    pub struct {}(pub {});", bt.name, bt.inner_path).unwrap();
            }
            TypeKind::Error => {
                let bname = error_bridge_name(&bt.name, &spec.module_name);
                writeln!(out, "    #[jac_error]").unwrap();
                writeln!(out, "    pub struct {};", bname).unwrap();
            }
        }
    }

    // ── impl blocks ───────────────────────────────────────────────────────────

    for bt in &spec.types {
        if bt.kind == TypeKind::Error {
            continue;
        }

        // A synthesized wrapper WITH a root producer gets a non-pub `wrap` ctor
        // (the ouroboros lifetime-erasure) emitted before its readers. A
        // nested-only wrapper has no root path — its instances are built inline by
        // the nested producer — so it gets no `wrap`.
        let wrap_src = bt
            .wrapper
            .as_ref()
            .and_then(|w| w.root.as_ref().map(|r| emit_wrap(w, r, bt)));
        let ctor_src = bt.ctor.as_ref().and_then(|f| emit_fn(f, bt, true));
        let method_srcs: Vec<String> = bt
            .methods
            .iter()
            .filter_map(|f| emit_fn(f, bt, false))
            .collect();

        if wrap_src.is_none()
            && ctor_src.is_none()
            && method_srcs.is_empty()
            && bt.injected_source.is_empty()
        {
            continue;
        }

        writeln!(out).unwrap();
        writeln!(out, "    impl {} {{", bt.name).unwrap();

        let mut first_fn = true;
        for src in wrap_src.into_iter().chain(ctor_src).chain(method_srcs) {
            if !first_fn {
                writeln!(out).unwrap();
            }
            writeln!(out, "{}", src).unwrap();
            first_fn = false;
        }
        for raw in &bt.injected_source {
            if !first_fn {
                writeln!(out).unwrap();
            }
            // raw snippets are written verbatim — overlay author is responsible for indentation
            write!(out, "{}", raw).unwrap();
            first_fn = false;
        }

        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}").unwrap();
    out
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// True for an opaque type with no bridgeable surface at all — nothing
/// constructs it and no method touches it, so it must not be emitted.
/// True if any bridged ctor or method returns a `HashMap<String, V>` (needs the
/// `HashMap` type in scope inside the generated module).
fn spec_has_map_return(spec: &BridgeSpec) -> bool {
    spec.types.iter().any(|bt| {
        bt.ctor
            .iter()
            .chain(bt.methods.iter())
            .any(|f| matches!(f.ret, BridgeReturn::Map(_)))
    })
}

fn is_dead_opaque(bt: &BridgeType) -> bool {
    bt.kind == TypeKind::Opaque
        && bt.ctor.is_none()
        && bt.methods.is_empty()
        && bt.injected_source.is_empty()
}

/// Error types whose source name is just `"Error"` are renamed to
/// `<Module>Error` so the bridge module has a distinct, namespaced identifier.
fn error_bridge_name(name: &str, module_name: &str) -> String {
    if name == "Error" {
        let mut cap = module_name.to_string();
        if let Some(first) = cap.get_mut(0..1) {
            first.make_ascii_uppercase();
        }
        format!("{}Error", cap)
    } else {
        name.to_string()
    }
}

/// `<'static>` (or `<'static, 'static>`, …) for an `n`-lifetime borrowed type.
fn static_args(n: usize) -> String {
    if n == 0 {
        return String::new();
    }
    let lts = vec!["'static"; n].join(", ");
    format!("<{lts}>")
}

/// Emit the ouroboros struct for a synthesized owning wrapper: the borrowing
/// value (lifetime erased to `'static`) declared before the owned input it
/// points into, so it drops first. The input is an `Arc<String>` so a NESTED
/// wrapper produced from this one (a `Match` from a `Captures`) can share the
/// exact same buffer via an Arc clone rather than re-owning a copy.
fn emit_wrapper_struct(out: &mut String, bt: &BridgeType, w: &OwningWrapper) {
    writeln!(out, "    pub struct {} {{", bt.name).unwrap();
    match &w.kind {
        WrapperKind::Owning => {
            writeln!(
                out,
                "        inner: {}{},",
                w.borrowed_path,
                static_args(w.lifetimes)
            )
            .unwrap();
            writeln!(out, "        _input: std::sync::Arc<String>,").unwrap();
        }
        // A cursor owns the iterator (both lifetimes erased) plus the owner and
        // input it borrows, each via `Arc`. Field order borrower-before-owners.
        WrapperKind::Cursor { .. } => {
            let owner = w
                .root
                .as_ref()
                .map(|r| r.owner_inner_path.as_str())
                .unwrap_or("()");
            writeln!(
                out,
                "        iter: {}{},",
                w.borrowed_path,
                static_args(w.lifetimes)
            )
            .unwrap();
            writeln!(out, "        _owner: std::sync::Arc<{owner}>,").unwrap();
            writeln!(out, "        _input: std::sync::Arc<String>,").unwrap();
        }
        // A drain owns only the eagerly-collected pieces — no lifetime survives.
        WrapperKind::Drain { .. } => {
            writeln!(out, "        items: Vec<String>,").unwrap();
        }
    }
    writeln!(out, "    }}").unwrap();
}

/// Emit the non-pub `wrap` constructor. The three wrapper kinds each own their
/// borrowed data differently (see [`WrapperKind`]).
fn emit_wrap(w: &OwningWrapper, root: &RootProducer, bt: &BridgeType) -> String {
    let owner = &root.owner_inner_path;
    let producer = &root.producer_call;
    let wname = &bt.name;
    match &w.kind {
        // find/captures: clone the input into an Arc<String>, produce the borrowed
        // value from it, erase the lifetime, store both. `None` (no match) in-band.
        WrapperKind::Owning => {
            let static_ty = format!("{}{}", w.borrowed_path, static_args(w.lifetimes));
            format!(
                "        fn wrap(owner: &{owner}, input: &str) -> Option<{wname}> {{\n\
                 \x20           let owned = std::sync::Arc::new(input.to_owned());\n\
                 \x20           let inner = owner.{producer}(owned.as_str())?;\n\
                 \x20           // SAFETY: `inner` borrows the `String` inside `owned`, whose Arc is\n\
                 \x20           // stored beside it and never mutated or moved-out; the borrower drops\n\
                 \x20           // before the owner, and every wrapper aliasing the buffer holds its own\n\
                 \x20           // Arc clone, so erasing to 'static is sound for the value's whole life.\n\
                 \x20           let inner: {static_ty} = unsafe {{ std::mem::transmute(inner) }};\n\
                 \x20           Some({wname} {{ inner, _input: owned }})\n\
                 \x20       }}",
            )
        }
        // find_iter: own the regex and haystack via Arc, build the iterator from
        // them, erase both its lifetimes. Always constructed (empty stream = live
        // handle whose first `next` is None), so no Option.
        WrapperKind::Cursor { .. } => {
            let static_ty = format!("{}{}", w.borrowed_path, static_args(w.lifetimes));
            format!(
                "        fn wrap(owner: &{owner}, input: &str) -> {wname} {{\n\
                 \x20           let owner = std::sync::Arc::new(owner.clone());\n\
                 \x20           let owned = std::sync::Arc::new(input.to_owned());\n\
                 \x20           // SAFETY: `iter` borrows `*owner` and `*owned`, both stored beside it\n\
                 \x20           // via Arc and never mutated or moved-out; each pulled item clones the\n\
                 \x20           // input Arc, so erasing both lifetimes to 'static is sound for the\n\
                 \x20           // cursor's whole life and every item it yields.\n\
                 \x20           let iter: {static_ty} =\n\
                 \x20               unsafe {{ std::mem::transmute(owner.{producer}(owned.as_str())) }};\n\
                 \x20           {wname} {{ iter, _owner: owner, _input: owned }}\n\
                 \x20       }}",
            )
        }
        // A drain eagerly copies its producer's string sequence into an owned
        // Vec<String> (no lifetime survives), stored reversed so `next` drains
        // front-to-back via pop(). The producer's own params are forwarded into
        // both the wrap signature and the call; how the return is turned into
        // owned Strings depends on the collection shape (see `DrainCollect`).
        WrapperKind::Drain { params, collect } => {
            let mut sig_parts: Vec<String> = vec![format!("owner: &{owner}")];
            for p in params {
                sig_parts.push(format!("{}: {}", p.name, scalar_ty(&p.ty)));
            }
            let sig = sig_parts.join(", ");
            let call_args = params
                .iter()
                .map(|p| p.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            let call = format!("owner.{producer}({call_args})");
            let collect_expr = match collect {
                DrainCollect::IterStr => format!("{call}.map(|s| s.to_owned()).collect()"),
                DrainCollect::VecString => call.clone(),
                DrainCollect::SliceString => format!("{call}.to_vec()"),
                DrainCollect::VecStr => {
                    format!("{call}.iter().map(|s| s.to_string()).collect()")
                }
            };
            format!(
                "        fn wrap({sig}) -> {wname} {{\n\
                 \x20           let mut items: Vec<String> = {collect_expr};\n\
                 \x20           items.reverse();\n\
                 \x20           {wname} {{ items }}\n\
                 \x20       }}",
            )
        }
    }
}

/// A `Wrapper::wrap(&self.0, args)` call, dropping the trailing comma when the
/// producer takes no forwarded args (a zero-param drain like `patterns`).
fn wrap_call(wrapper: &str, args_str: &str) -> String {
    if args_str.is_empty() {
        format!("{wrapper}::wrap(&self.0)")
    } else {
        format!("{wrapper}::wrap(&self.0, {args_str})")
    }
}

/// The Rust source type for a scalar param at the bridge boundary.
fn scalar_ty(t: &ScalarType) -> String {
    match t {
        ScalarType::Str => "&str".into(),
        ScalarType::Bool => "bool".into(),
        ScalarType::Callback => "JacCallback".into(),
        ScalarType::Int(rust) | ScalarType::Uint(rust) => rust.clone(),
        // 1.2.2: a byte string re-declared as `&[u8]`, which satisfies an
        // `AsRef<[u8]>` bound (sha2's `update`), so `self.0.update(data)` compiles.
        ScalarType::Bytes => "&[u8]".into(),
        // 2.8: a serde-wide param re-declared inside the `Wide<…>` marker (a
        // serde-transparent newtype the macro imports from the rt module). The
        // body unwraps `.0` before the inner call (see `call_args` in `emit_fn`).
        ScalarType::Wide(inner) => format!("Wide<{inner}>"),
    }
}

/// Render one function (constructor or method) as indented bridge source.
///
/// `classify` only admits params `ScalarType` can represent (`&str`, `bool`);
/// anything else is already a recorded skip, so this always emits.
fn emit_fn(f: &BridgeFn, bt: &BridgeType, is_ctor: bool) -> Option<String> {
    // A STATIC (1.3) has no receiver, exactly like a ctor — it calls through the
    // associated form `Type::fn(args)` — but lives in `methods` and is stamped
    // `#[jac(assoc)]` so the macro tags it FN_STATIC rather than FN_CTOR.
    let no_recv = is_ctor || f.is_static;

    // Signature param list.
    let mut sig_parts: Vec<String> = Vec::new();
    if !no_recv {
        // A cursor/drain pull method mutates the iterator it owns; a 1.2.2
        // `&mut self` source method (`Digest::update`) mutates the handle in place
        // (the macro routes it through the reentrancy busy-latch). A consuming
        // (`self`) method keeps a `&self` shim and clones the value out below.
        sig_parts.push(match f.recv {
            Recv::IterNext | Recv::DrainNext => "&mut self".into(),
            _ if f.self_mut => "&mut self".into(),
            _ => "&self".into(),
        });
    }
    for p in &f.params {
        sig_parts.push(format!("{}: {}", p.name, scalar_ty(&p.ty)));
    }
    let params_str = sig_parts.join(", ");
    // Forwarded param NAMES — used by the owning-wrapper / replacer arms, whose
    // params are always `&str` (never wide), so no unwrap is needed.
    let args_str = f
        .params
        .iter()
        .map(|p| p.name.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    // 2.8: the inner-call argument list. A wide param arrives as `Wide<T>`, so the
    // body passes its transparent `.0` to the source method; every other param
    // forwards by name unchanged. Used inside `base_call`.
    let call_args = f
        .params
        .iter()
        .map(|p| match p.ty {
            ScalarType::Wide(_) => format!("{}.0", p.name),
            _ => p.name.clone(),
        })
        .collect::<Vec<_>>()
        .join(", ");

    let inner = &bt.inner_path;
    // `fname` is the Rust call target; the emitted `pub fn` uses the exposed
    // (possibly overlay-renamed) name so the Jac side sees the nicer identifier.
    let fname = &f.name;
    let exposed = f.exposed();
    // Receiver a method body delegates through: the newtype field for ordinary
    // methods, the erased borrowing value for a synthesized wrapper's readers.
    let recv = match f.recv {
        Recv::Field0 => "self.0",
        Recv::Inner => "self.inner",
        Recv::IterNext => "self.iter",
        Recv::DrainNext => "self.items",
    };

    // For async source APIs, append `.await` to the inner call so the macro
    // sees an `async fn` and emits a blocking C shim for it.
    let aw = if f.is_async { ".await" } else { "" };
    // A consuming-`self` method (`Digest::finalize(self)`) can't move out of the
    // shared handle, so it clones the value first: `self.0.clone().finalize()`.
    // Gated on the inner type being `Clone` in the classifier, so this compiles.
    let recv_expr = if f.consumes_self {
        format!("{recv}.clone()")
    } else {
        recv.to_string()
    };
    // A method flattened off a trait (`via_trait`) is called through UFCS
    // (`Digest::update(&mut self.0, data)`) rather than method syntax
    // (`self.0.update(data)`). Two flattened traits can expose the same method name
    // (sha2 brings both `Digest` and `DynDigest` into scope, each with
    // `update`/`finalize`/`reset`), which makes `self.0.update(..)` ambiguous
    // (E0034); naming the trait disambiguates. The receiver is borrowed to match
    // the source receiver: `&mut self.0` for a `&mut self` method, `self.0.clone()`
    // (by value) for a consuming method, `&self.0` otherwise.
    let via_trait_short = f.via_trait.as_deref().map(|p| p.rsplit("::").next().unwrap_or(p));
    let ufcs_recv = if f.consumes_self {
        format!("{recv}.clone()")
    } else if f.self_mut {
        format!("&mut {recv}")
    } else {
        format!("&{recv}")
    };
    // Build the base call expression (before any post-call transforms). Uses
    // `call_args` (wide params unwrapped to `.0`) as the inner argument list.
    let base_call = |r: &str| -> String {
        if is_ctor {
            format!("{inner}::{fname}({call_args}){aw}")
        } else if f.is_static {
            // A static calls through the associated form. When flattened off a
            // trait (`Sha256::digest` via `Digest`), fully-qualify it as
            // `<Inner as Trait>::fname` so an overlapping same-named item on a
            // sibling trait in scope (sha2 brings both `Digest` and `DynDigest`)
            // can't make the call ambiguous (E0034).
            match via_trait_short {
                Some(tr) => format!("<{inner} as {tr}>::{fname}({call_args}){aw}"),
                None => format!("{inner}::{fname}({call_args}){aw}"),
            }
        } else if let Some(tr) = via_trait_short {
            let sep = if call_args.is_empty() { "" } else { ", " };
            format!("{tr}::{fname}({ufcs_recv}{sep}{call_args}){aw}")
        } else {
            format!("{r}.{fname}({call_args}){aw}")
        }
    };

    let (ret_ann, body): (String, String) = match &f.ret {
        BridgeReturn::Void => (String::new(), base_call(&recv_expr)),
        BridgeReturn::Bool => (" -> bool".into(), base_call(&recv_expr)),
        BridgeReturn::Str => {
            // Bridge macro expects `String` (not `&str`) so convert via to_string().
            (
                " -> String".into(),
                format!("{}.to_string()", base_call(&recv_expr)),
            )
        }
        BridgeReturn::Int(rust)
        | BridgeReturn::Uint(rust)
        | BridgeReturn::Map(rust)
        | BridgeReturn::List(rust) => {
            // Integer / HashMap<String,V> / Vec<V> returns cross verbatim — the
            // macro tags the width (TAG_INT/TAG_UINT) and marshals the container
            // into a real Jac dict/list. The wrapper just forwards the value.
            (format!(" -> {rust}"), base_call(&recv_expr))
        }
        // 1.2.2: a byte-string return crosses as an owned `Vec<u8>` (TAG_BYTES).
        // `.to_vec()` turns a digest's `GenericArray`/`[u8]` into an owned Vec and
        // is a shape-preserving clone on a `Vec<u8>` source.
        BridgeReturn::Bytes => (
            " -> Vec<u8>".into(),
            format!("{}.to_vec()", base_call(&recv_expr)),
        ),
        BridgeReturn::OwnSelf => {
            // `base_call` already spells the ctor (`inner::new()`) vs method
            // (`self.0.f()`) form; both wrap in `Self(..)`.
            let call = format!("Self({})", base_call(&recv_expr));
            (" -> Self".into(), call)
        }
        BridgeReturn::OwnSelfResult => {
            let call = format!(
                "{}.map(Self).map_err(|e| e.to_string())",
                base_call(&recv_expr)
            );
            (" -> Result<Self, String>".into(), call)
        }
        // 1.2.4: a fresh owned instance of ANOTHER bridged type. Wrap the call in
        // that type's newtype (`NaiveDateTime(self.0.and_hms(…))`); the macro tags
        // the return `TAG_REF|idx` and the loader instantiates that type's wrapper.
        BridgeReturn::Ref(name) => (
            format!(" -> {name}"),
            format!("{name}({})", base_call(&recv_expr)),
        ),
        // 1.2.4: `Option<BridgedType>` / `Option<Self>` — map the present case into
        // the target newtype; `None` crosses in-band as a null handle.
        BridgeReturn::OptRef(name) => (
            format!(" -> Option<{name}>"),
            format!("{}.map({name})", base_call(&recv_expr)),
        ),
        // 2.8: a serde-wide return — wrap the value in the `Wide<…>` marker; the
        // macro serializes it to a MessagePack `JacBuf` (TAG_WIDE). The inner type
        // is spelled by the classifier (a local path or whitelisted std shape).
        BridgeReturn::Wide(inner) => (
            format!(" -> Wide<{inner}>"),
            format!("Wide({})", base_call(&recv_expr)),
        ),
        BridgeReturn::OptWrapper(wrapper) => match f.recv {
            // Root producer (on a plain owner): delegate to the wrapper's `wrap`
            // ctor, which owns the input and erases the borrow.
            Recv::Field0 => {
                let call = wrap_call(wrapper, &args_str);
                (format!(" -> Option<{}>", wrapper), call)
            }
            // Nested producer (a reader on ANOTHER wrapper): build the child inline
            // from this wrapper's already-'static borrowing value, sharing the owned
            // buffer via an Arc clone. No transmute, no new allocation — the parent
            // is 'static, so its produced value is too, and the Arc clone keeps the
            // shared buffer alive for the child's whole life.
            Recv::Inner => {
                let call = format!(
                    "let inner = self.inner.{}({})?;\n            \
                     Some({} {{ inner, _input: std::sync::Arc::clone(&self._input) }})",
                    fname, args_str, wrapper
                );
                (format!(" -> Option<{}>", wrapper), call)
            }
            // Cursor pull: take the next item from the owned iterator and wrap it,
            // sharing the cursor's input Arc — the nested rule, applied per pull.
            // The item is already 'static (the iterator is), so no transmute.
            Recv::IterNext => {
                let call = format!(
                    "let inner = self.iter.next()?;\n            \
                     Some({} {{ inner, _input: std::sync::Arc::clone(&self._input) }})",
                    wrapper
                );
                (format!(" -> Option<{}>", wrapper), call)
            }
            Recv::DrainNext => unreachable!("DrainNext yields OptStr, not OptWrapper"),
        },
        // Non-nullable cursor/drain producer: build the wrapper via its `wrap` ctor.
        BridgeReturn::Wrapper(wrapper) => {
            let call = wrap_call(wrapper, &args_str);
            (format!(" -> {}", wrapper), call)
        }
        // Drain pull: pop the next owned piece front-to-back. None ends the drain.
        BridgeReturn::OptStr => (" -> Option<String>".into(), "self.items.pop()".into()),
        // CALLBACK: replace_all with a JacCallback. Rust calls back into Jac once
        // per match; the callback returns each match's replacement. The closure
        // can't itself return a Result, so capture the first callback error and
        // surface it as this method's Err after the walk. Matches the proof crate
        // (jac-bridge-owning) body exactly.
        BridgeReturn::ReplacerResult(captures_path) => {
            // params are [haystack: &str, rep: JacCallback] by construction.
            let haystack = f
                .params
                .first()
                .map(|p| p.name.as_str())
                .unwrap_or("haystack");
            let repname = f.params.get(1).map(|p| p.name.as_str()).unwrap_or("rep");
            let body = format!(
                "let err: std::cell::RefCell<Option<String>> = std::cell::RefCell::new(None);\n            \
                 let out = {recv}.{fname}({haystack}, |caps: &{captures_path}| {{\n                \
                     let m = caps.get(0).map_or(\"\", |x| x.as_str());\n                \
                     match {repname}.call(m) {{\n                        \
                         Ok(s) => s,\n                        \
                         Err(e) => {{\n                            \
                             if err.borrow().is_none() {{ *err.borrow_mut() = Some(e); }}\n                            \
                             String::new()\n                        \
                         }}\n                    \
                     }}\n                \
                 }}).into_owned();\n            \
                 match err.into_inner() {{ Some(e) => Err(e), None => Ok(out) }}"
            );
            (" -> Result<String, String>".into(), body)
        }
    };

    let async_kw = if f.is_async { "async " } else { "" };
    // Phase S: stamp the ownership helper attribute on non-`Owned` handle returns
    // so the macro ORs the ownership bit into the `Ref` return tag. `Owned` (the
    // default, and every ctor / fresh-object / owning-wrapper return) emits
    // nothing — the generated source stays byte-identical to pre-Phase-S output,
    // which is what keeps `coverage-baseline.toml` and the golden fixtures pinned.
    let own_attr = match f.ret_ownership {
        Ownership::Owned => String::new(),
        // `Shared` is retired: no classifier path produces it and the overlay
        // rejects `ownership = "shared"` (Phase 1.2.4), so it can never reach
        // codegen. The variant survives only to keep the ABI bit reserved.
        Ownership::Shared => unreachable!(
            "Ownership::Shared is retired — the overlay rejects `shared`; a co-owned \
             handle is a `&Self` return, not a stamped attribute"
        ),
        Ownership::Borrowed => "        #[jac(borrowed)]\n".into(),
    };
    // 1.3: a static is stamped `#[jac(assoc)]` so the macro tags it FN_STATIC
    // (a no-receiver fn dispatched by name with no handle). Statics are always
    // `Owned`, so `assoc` never coexists with `borrowed`.
    let assoc_attr = if f.is_static {
        "        #[jac(assoc)]\n"
    } else {
        ""
    };
    Some(format!(
        "{assoc_attr}{own_attr}        pub {async_kw}fn {}({}){} {{\n            {}\n        }}",
        exposed, params_str, ret_ann, body
    ))
}
