//! Regex bridge generated by #[jac_bridge::bridge] (M2).
//!
//! Verify equivalence with jac-bridge-regex/src/lib.rs (the hand-written M0
//! baseline): both crates export the same C symbols and embed the same D2 blob.
//!
//! Exported C symbols (identical to the hand-written bridge):
//!   jac_regex_Regex_new, jac_regex_Regex_is_match, jac_regex_Regex_drop
//!   jac_regex_error_message, jac_regex_error_drop, jac_regex_free_buf
//!   jac_bridge_init_regex

#![allow(clippy::missing_safety_doc)]

use jac_bridge::bridge;

#[bridge(module = "regex")]
mod bridge_impl {
    /// Opaque handle wrapping a compiled regex::Regex.
    pub struct Regex(pub regex::Regex);

    /// Named error type for D2 metadata.
    /// At runtime, error handles are Box<String>; this struct is a name-only marker.
    #[jac_error]
    pub struct RegexError;

    impl Regex {
        /// Compile `pattern`. Returns STATUS_ERR on invalid syntax.
        pub fn new(pattern: &str) -> Result<Self, String> {
            regex::Regex::new(pattern).map(Self).map_err(|e| e.to_string())
        }

        /// Test whether `text` matches this regex.
        pub fn is_match(&self, text: &str) -> bool {
            self.0.is_match(text)
        }
    }
}

// ─── tests ────────────────────────────────────────────────────────────────────
//
// Mirror the jac-bridge-regex test suite exactly, exercising the same
// ABI invariants against the macro-generated shims.

#[cfg(test)]
mod tests {
    use std::mem::MaybeUninit;

    // Re-export the generated shims under the same names the tests use.
    use super::{
        jac_regex_Regex_new, jac_regex_Regex_is_match, jac_regex_Regex_drop,
        jac_regex_error_message, jac_regex_error_drop, jac_regex_free_buf,
        jac_bridge_init_regex,
        __jac_bridge_regex_rt::JacBuf,
    };

    const STATUS_OK:    i32 = 0;
    const STATUS_ERR:   i32 = 1;
    const STATUS_PANIC: i32 = 2;

    unsafe fn compile(pattern: &str) -> u64 {
        let mut h = 0u64; let mut e = 0u64;
        let st = jac_regex_Regex_new(
            pattern.as_ptr(), pattern.len() as u32, &mut h, &mut e,
        );
        assert_eq!(st, STATUS_OK, "unexpected compile failure");
        assert_ne!(h, 0); assert_eq!(e, 0);
        h
    }

    unsafe fn is_match(handle: u64, text: &str) -> bool {
        let mut b = 0u8; let mut e = 0u64;
        let st = jac_regex_Regex_is_match(
            handle, text.as_ptr(), text.len() as u32, &mut b, &mut e,
        );
        assert_eq!(st, STATUS_OK); assert_eq!(e, 0);
        b != 0
    }

    #[test]
    fn test_match_and_no_match() {
        unsafe {
            let h = compile(r"foo\d+");
            assert!(is_match(h, "foo42"));
            assert!(!is_match(h, "bar99"));
            jac_regex_Regex_drop(h);
        }
    }

    #[test]
    fn test_ptr_len_no_nul_reliance() {
        unsafe {
            let raw = b"hello\x00extra";
            let mut h = 0u64; let mut e = 0u64;
            let st = jac_regex_Regex_new(raw.as_ptr(), 5, &mut h, &mut e);
            assert_eq!(st, STATUS_OK);
            let text = b"hello\x00world";
            let mut b = 0u8; let mut be = 0u64;
            let st2 = jac_regex_Regex_is_match(h, text.as_ptr(), 5, &mut b, &mut be);
            assert_eq!(st2, STATUS_OK);
            assert_eq!(b, 1);
            jac_regex_Regex_drop(h);
        }
    }

    #[test]
    fn test_drop_zero_is_noop() {
        unsafe { jac_regex_Regex_drop(0); jac_regex_error_drop(0); }
    }

    #[test]
    fn test_explicit_close_then_zero_drop() {
        unsafe {
            let h = compile("abc");
            jac_regex_Regex_drop(h);
            jac_regex_Regex_drop(0);
        }
    }

    #[test]
    fn test_invalid_pattern_returns_error_handle() {
        unsafe {
            let pat = b"(unclosed";
            let mut h = 0u64; let mut e = 0u64;
            let st = jac_regex_Regex_new(pat.as_ptr(), pat.len() as u32, &mut h, &mut e);
            assert_eq!(st, STATUS_ERR);
            assert_eq!(h, 0);
            assert_ne!(e, 0);

            let mut buf = MaybeUninit::<JacBuf>::uninit();
            let mut be = 0u64;
            let bst = jac_regex_error_message(e, buf.as_mut_ptr(), &mut be);
            assert_eq!(bst, STATUS_OK);
            let buf = buf.assume_init();
            assert!(buf.len > 0);
            let msg = std::str::from_utf8(
                std::slice::from_raw_parts(buf.ptr, buf.len as usize)
            ).unwrap();
            assert!(!msg.is_empty());
            jac_regex_free_buf(buf);
            jac_regex_error_drop(e);
        }
    }

    #[test]
    fn test_free_buf_without_double_free() {
        unsafe {
            let pat = b"[bad";
            let mut h = 0u64; let mut e = 0u64;
            jac_regex_Regex_new(pat.as_ptr(), pat.len() as u32, &mut h, &mut e);
            assert_ne!(e, 0);
            let mut buf1 = MaybeUninit::<JacBuf>::uninit();
            let mut be = 0u64;
            jac_regex_error_message(e, buf1.as_mut_ptr(), &mut be);
            let buf1 = buf1.assume_init();
            let mut buf2 = MaybeUninit::<JacBuf>::uninit();
            jac_regex_error_message(e, buf2.as_mut_ptr(), &mut be);
            let buf2 = buf2.assume_init();
            jac_regex_free_buf(buf1);
            jac_regex_free_buf(buf2);
            jac_regex_error_drop(e);
        }
    }

    // ── D2 metadata checks ───────────────────────────────────────────────────

    #[test]
    fn test_metadata_magic() {
        assert_eq!(&super::__JAC_BRIDGE_META[0..8], b"JACBRDG1");
    }

    #[test]
    fn test_metadata_abi_version() {
        let blob = &super::__JAC_BRIDGE_META;
        assert_eq!(u32::from_le_bytes(blob[8..12].try_into().unwrap()), 1);
    }

    #[test]
    fn test_metadata_blob_len() {
        let blob = &super::__JAC_BRIDGE_META;
        let reported = u32::from_le_bytes(blob[16..20].try_into().unwrap()) as usize;
        assert_eq!(reported, blob.len());
    }

    #[test]
    fn test_metadata_type_and_fn_counts() {
        let blob = &super::__JAC_BRIDGE_META;
        let types = u32::from_le_bytes(blob[44..48].try_into().unwrap());
        let fns   = u32::from_le_bytes(blob[52..56].try_into().unwrap());
        assert_eq!(types, 2, "expected Regex + RegexError");
        assert_eq!(fns,   3, "expected new + is_match + message");
    }

    #[test]
    fn test_metadata_module_name() {
        let blob = &super::__JAC_BRIDGE_META;
        let off = u32::from_le_bytes(blob[24..28].try_into().unwrap()) as usize;
        let len = u32::from_le_bytes(blob[28..32].try_into().unwrap()) as usize;
        assert_eq!(std::str::from_utf8(&blob[off..off+len]).unwrap(), "regex");
    }

    #[test]
    fn test_metadata_type0_opaque_and_drop() {
        let blob = &super::__JAC_BRIDGE_META;
        let td0 = 56usize;
        assert_eq!(blob[td0 + 4], 0, "Regex must be opaque (kind=0)");
        let no = u32::from_le_bytes(blob[td0+8..td0+12].try_into().unwrap()) as usize;
        let nl = u32::from_le_bytes(blob[td0+12..td0+16].try_into().unwrap()) as usize;
        assert_eq!(&blob[no..no+nl], b"Regex");
        let do_ = u32::from_le_bytes(blob[td0+16..td0+20].try_into().unwrap()) as usize;
        let dl  = u32::from_le_bytes(blob[td0+20..td0+24].try_into().unwrap()) as usize;
        assert_eq!(&blob[do_..do_+dl], b"jac_regex_Regex_drop");
    }

    #[test]
    fn test_metadata_type1_error_and_drop() {
        let blob = &super::__JAC_BRIDGE_META;
        let td1 = 88usize;
        assert_eq!(blob[td1 + 4], 3, "RegexError must be error (kind=3)");
        let no = u32::from_le_bytes(blob[td1+8..td1+12].try_into().unwrap()) as usize;
        let nl = u32::from_le_bytes(blob[td1+12..td1+16].try_into().unwrap()) as usize;
        assert_eq!(&blob[no..no+nl], b"RegexError");
        let do_ = u32::from_le_bytes(blob[td1+16..td1+20].try_into().unwrap()) as usize;
        let dl  = u32::from_le_bytes(blob[td1+20..td1+24].try_into().unwrap()) as usize;
        assert_eq!(&blob[do_..do_+dl], b"jac_regex_error_drop");
    }

    #[test]
    fn test_metadata_fn0_new_ctor() {
        let blob = &super::__JAC_BRIDGE_META;
        let fd0 = 56 + 2 * 32; // 120
        // name = "new"
        let no = u32::from_le_bytes(blob[fd0+4..fd0+8].try_into().unwrap()) as usize;
        let nl = u32::from_le_bytes(blob[fd0+8..fd0+12].try_into().unwrap()) as usize;
        assert_eq!(&blob[no..no+nl], b"new");
        // kind = 0 (ctor)
        assert_eq!(blob[fd0 + 24], 0);
        // throws = 1 (RegexError)
        let throws = u32::from_le_bytes(blob[fd0+28..fd0+32].try_into().unwrap());
        assert_eq!(throws, 1);
        // ret = TYPE_REF(0) = Regex
        let ret = u32::from_le_bytes(blob[fd0+32..fd0+36].try_into().unwrap());
        assert_eq!(ret, 0x8000_0000u32);
    }

    #[test]
    fn test_metadata_fn1_is_match_method() {
        let blob = &super::__JAC_BRIDGE_META;
        let fd1 = 56 + 2 * 32 + 44; // 164
        // kind = 1 (method)
        assert_eq!(blob[fd1 + 24], 1);
        // self_type = 0 (Regex)
        let st = u32::from_le_bytes(blob[fd1+20..fd1+24].try_into().unwrap());
        assert_eq!(st, 0);
        // ret = TAG_BOOL = 1
        let ret = u32::from_le_bytes(blob[fd1+32..fd1+36].try_into().unwrap());
        assert_eq!(ret, 1);
        // throws = NONE
        let throws = u32::from_le_bytes(blob[fd1+28..fd1+32].try_into().unwrap());
        assert_eq!(throws, 0xFFFF_FFFFu32);
    }

    #[test]
    fn test_metadata_fn2_message_method() {
        let blob = &super::__JAC_BRIDGE_META;
        let fd2 = 56 + 2 * 32 + 2 * 44; // 208
        // kind = 1 (method), self = 1 (RegexError), ret = TAG_STR = 4
        assert_eq!(blob[fd2 + 24], 1);
        let st = u32::from_le_bytes(blob[fd2+20..fd2+24].try_into().unwrap());
        assert_eq!(st, 1);
        let ret = u32::from_le_bytes(blob[fd2+32..fd2+36].try_into().unwrap());
        assert_eq!(ret, 4);
    }

    #[test]
    fn test_init_returns_meta_ptr() {
        let ptr = unsafe { jac_bridge_init_regex() };
        assert!(!ptr.is_null());
        let slice = unsafe { std::slice::from_raw_parts(ptr, 8) };
        assert_eq!(slice, b"JACBRDG1");
    }

    // ── M2 expansion diff-test ────────────────────────────────────────────────
    //
    // The whole point of the macro: it must reproduce the hand-written M0
    // reference vector *byte for byte*. Not merely structurally equivalent —
    // identical, so the na compiler and ctypes loader parse the same bytes
    // whether the bridge was hand-written or macro-generated.
    #[test]
    fn test_macro_output_matches_reference_vector() {
        let reference = include_bytes!("../../reference/regex.jacbridge");
        assert_eq!(
            &super::__JAC_BRIDGE_META[..], &reference[..],
            "macro-generated blob diverged from the hand-written reference vector"
        );
    }
}
