// Auto-generated by jac-bridge-binder. Do not edit.
// crate: regex  version: 1.12.4

use jac_bridge::bridge;

#[bridge(module = "regex")]
#[allow(dead_code)]
mod bridge_impl {
    pub struct CaptureLocations(pub regex::CaptureLocations);

    pub struct OwnedCaptureMatches {
        iter: regex::CaptureMatches<'static, 'static>,
        _owner: std::sync::Arc<regex::Regex>,
        _input: std::sync::Arc<String>,
    }

    pub struct OwnedCaptures {
        inner: regex::Captures<'static>,
        _input: std::sync::Arc<String>,
    }

    pub struct OwnedMatch {
        inner: regex::Match<'static>,
        _input: std::sync::Arc<String>,
    }

    pub struct OwnedMatches {
        iter: regex::Matches<'static, 'static>,
        _owner: std::sync::Arc<regex::Regex>,
        _input: std::sync::Arc<String>,
    }

    pub struct OwnedPatterns {
        items: Vec<String>,
    }

    pub struct OwnedSplit {
        items: Vec<String>,
    }

    pub struct OwnedSplitN {
        items: Vec<String>,
    }

    pub struct Regex(pub regex::Regex);

    pub struct RegexBuilder(pub regex::RegexBuilder);

    pub struct RegexSet(pub regex::RegexSet);

    pub struct RegexSetBuilder(pub regex::RegexSetBuilder);

    pub struct SetMatches(pub regex::SetMatches);

    #[jac_error]
    pub struct RegexError;

    impl CaptureLocations {
        pub fn len(&self) -> usize {
            self.0.len()
        }
    }

    impl OwnedCaptureMatches {
        fn wrap(owner: &regex::Regex, input: &str) -> OwnedCaptureMatches {
            let owner = std::sync::Arc::new(owner.clone());
            let owned = std::sync::Arc::new(input.to_owned());
            // SAFETY: `iter` borrows `*owner` and `*owned`, both stored beside it
            // via Arc and never mutated or moved-out; each pulled item clones the
            // input Arc, so erasing both lifetimes to 'static is sound for the
            // cursor's whole life and every item it yields.
            let iter: regex::CaptureMatches<'static, 'static> =
                unsafe { std::mem::transmute(owner.captures_iter(owned.as_str())) };
            OwnedCaptureMatches { iter, _owner: owner, _input: owned }
        }

        pub fn next(&mut self) -> Option<OwnedCaptures> {
            let inner = self.iter.next()?;
            Some(OwnedCaptures { inner, _input: std::sync::Arc::clone(&self._input) })
        }
    }

    impl OwnedCaptures {
        fn wrap(owner: &regex::Regex, input: &str) -> Option<OwnedCaptures> {
            let owned = std::sync::Arc::new(input.to_owned());
            let inner = owner.captures(owned.as_str())?;
            // SAFETY: `inner` borrows the `String` inside `owned`, whose Arc is
            // stored beside it and never mutated or moved-out; the borrower drops
            // before the owner, and every wrapper aliasing the buffer holds its own
            // Arc clone, so erasing to 'static is sound for the value's whole life.
            let inner: regex::Captures<'static> = unsafe { std::mem::transmute(inner) };
            Some(OwnedCaptures { inner, _input: owned })
        }

        pub fn get(&self, i: usize) -> Option<OwnedMatch> {
            let inner = self.inner.get(i)?;
            Some(OwnedMatch { inner, _input: std::sync::Arc::clone(&self._input) })
        }

        pub fn get_match(&self) -> OwnedMatch {
            let inner = self.inner.get_match();
            OwnedMatch { inner, _input: std::sync::Arc::clone(&self._input) }
        }

        pub fn len(&self) -> usize {
            self.inner.len()
        }

        pub fn name(&self, name: &str) -> Option<OwnedMatch> {
            let inner = self.inner.name(name)?;
            Some(OwnedMatch { inner, _input: std::sync::Arc::clone(&self._input) })
        }
    }

    impl OwnedMatch {
        fn wrap(owner: &regex::Regex, input: &str) -> Option<OwnedMatch> {
            let owned = std::sync::Arc::new(input.to_owned());
            let inner = owner.find(owned.as_str())?;
            // SAFETY: `inner` borrows the `String` inside `owned`, whose Arc is
            // stored beside it and never mutated or moved-out; the borrower drops
            // before the owner, and every wrapper aliasing the buffer holds its own
            // Arc clone, so erasing to 'static is sound for the value's whole life.
            let inner: regex::Match<'static> = unsafe { std::mem::transmute(inner) };
            Some(OwnedMatch { inner, _input: owned })
        }

        pub fn as_str(&self) -> String {
            self.inner.as_str().to_string()
        }

        pub fn end(&self) -> usize {
            self.inner.end()
        }

        pub fn is_empty(&self) -> bool {
            self.inner.is_empty()
        }

        pub fn len(&self) -> usize {
            self.inner.len()
        }

        pub fn start(&self) -> usize {
            self.inner.start()
        }
    }

    impl OwnedMatches {
        fn wrap(owner: &regex::Regex, input: &str) -> OwnedMatches {
            let owner = std::sync::Arc::new(owner.clone());
            let owned = std::sync::Arc::new(input.to_owned());
            // SAFETY: `iter` borrows `*owner` and `*owned`, both stored beside it
            // via Arc and never mutated or moved-out; each pulled item clones the
            // input Arc, so erasing both lifetimes to 'static is sound for the
            // cursor's whole life and every item it yields.
            let iter: regex::Matches<'static, 'static> =
                unsafe { std::mem::transmute(owner.find_iter(owned.as_str())) };
            OwnedMatches { iter, _owner: owner, _input: owned }
        }

        pub fn next(&mut self) -> Option<OwnedMatch> {
            let inner = self.iter.next()?;
            Some(OwnedMatch { inner, _input: std::sync::Arc::clone(&self._input) })
        }
    }

    impl OwnedPatterns {
        fn wrap(owner: &regex::RegexSet) -> OwnedPatterns {
            let mut items: Vec<String> = owner.patterns().to_vec();
            items.reverse();
            OwnedPatterns { items }
        }

        pub fn next(&mut self) -> Option<String> {
            self.items.pop()
        }
    }

    impl OwnedSplit {
        fn wrap(owner: &regex::Regex, haystack: &str) -> OwnedSplit {
            let mut items: Vec<String> = owner.split(haystack).map(|s| s.to_owned()).collect();
            items.reverse();
            OwnedSplit { items }
        }

        pub fn next(&mut self) -> Option<String> {
            self.items.pop()
        }
    }

    impl OwnedSplitN {
        fn wrap(owner: &regex::Regex, haystack: &str, limit: usize) -> OwnedSplitN {
            let mut items: Vec<String> = owner.splitn(haystack, limit).map(|s| s.to_owned()).collect();
            items.reverse();
            OwnedSplitN { items }
        }

        pub fn next(&mut self) -> Option<String> {
            self.items.pop()
        }
    }

    impl Regex {
        pub fn new(re: &str) -> Result<Self, String> {
            regex::Regex::new(re).map(Self).map_err(|e| e.to_string())
        }

        pub fn matches(&self, haystack: &str) -> bool {
            self.0.is_match(haystack)
        }

        pub fn find(&self, haystack: &str) -> Option<OwnedMatch> {
            OwnedMatch::wrap(&self.0, haystack)
        }

        pub fn find_iter(&self, haystack: &str) -> OwnedMatches {
            OwnedMatches::wrap(&self.0, haystack)
        }

        pub fn captures(&self, haystack: &str) -> Option<OwnedCaptures> {
            OwnedCaptures::wrap(&self.0, haystack)
        }

        pub fn captures_iter(&self, haystack: &str) -> OwnedCaptureMatches {
            OwnedCaptureMatches::wrap(&self.0, haystack)
        }

        pub fn split(&self, haystack: &str) -> OwnedSplit {
            OwnedSplit::wrap(&self.0, haystack)
        }

        pub fn splitn(&self, haystack: &str, limit: usize) -> OwnedSplitN {
            OwnedSplitN::wrap(&self.0, haystack, limit)
        }

        pub fn replace(&self, haystack: &str, rep: JacCallback) -> Result<String, String> {
            let err: std::cell::RefCell<Option<String>> = std::cell::RefCell::new(None);
            let out = self.0.replace(haystack, |caps: &regex::Captures| {
                let m = caps.get(0).map_or("", |x| x.as_str());
                match rep.call(m) {
                        Ok(s) => s,
                        Err(e) => {
                            if err.borrow().is_none() { *err.borrow_mut() = Some(e); }
                            String::new()
                        }
                    }
                }).into_owned();
            match err.into_inner() { Some(e) => Err(e), None => Ok(out) }
        }

        pub fn replace_all(&self, haystack: &str, rep: JacCallback) -> Result<String, String> {
            let err: std::cell::RefCell<Option<String>> = std::cell::RefCell::new(None);
            let out = self.0.replace_all(haystack, |caps: &regex::Captures| {
                let m = caps.get(0).map_or("", |x| x.as_str());
                match rep.call(m) {
                        Ok(s) => s,
                        Err(e) => {
                            if err.borrow().is_none() { *err.borrow_mut() = Some(e); }
                            String::new()
                        }
                    }
                }).into_owned();
            match err.into_inner() { Some(e) => Err(e), None => Ok(out) }
        }

        pub fn replacen(&self, haystack: &str, limit: usize, rep: &str) -> String {
            self.0.replacen(haystack, limit, rep).to_string()
        }

        pub fn shortest_match(&self, haystack: &str) -> Option<usize> {
            self.0.shortest_match(haystack)
        }

        pub fn shortest_match_at(&self, haystack: &str, start: usize) -> Option<usize> {
            self.0.shortest_match_at(haystack, start)
        }

        pub fn is_match_at(&self, haystack: &str, start: usize) -> bool {
            self.0.is_match_at(haystack, start)
        }

        pub fn find_at(&self, haystack: &str, start: usize) -> Option<OwnedMatch> {
            let owned = std::sync::Arc::new(haystack.to_owned());
            let inner = self.0.find_at(owned.as_str(), start)?;
            // SAFETY: `inner` borrows the `String` inside `owned`, whose Arc is
            // stored beside it and never mutated or moved-out; the borrower drops
            // before the owner, so erasing to 'static is sound for the value's
            // whole life (same argument as the shared `wrap` ctor).
            let inner: regex::Match<'static> = unsafe { std::mem::transmute(inner) };
            Some(OwnedMatch { inner, _input: owned })
        }

        pub fn captures_at(&self, haystack: &str, start: usize) -> Option<OwnedCaptures> {
            let owned = std::sync::Arc::new(haystack.to_owned());
            let inner = self.0.captures_at(owned.as_str(), start)?;
            // SAFETY: `inner` borrows the `String` inside `owned`, whose Arc is
            // stored beside it and never mutated or moved-out; the borrower drops
            // before the owner, so erasing to 'static is sound for the value's
            // whole life (same argument as the shared `wrap` ctor).
            let inner: regex::Captures<'static> = unsafe { std::mem::transmute(inner) };
            Some(OwnedCaptures { inner, _input: owned })
        }

        pub fn as_str(&self) -> String {
            self.0.as_str().to_string()
        }

        pub fn captures_len(&self) -> usize {
            self.0.captures_len()
        }

        pub fn static_captures_len(&self) -> Option<usize> {
            self.0.static_captures_len()
        }

        pub fn capture_locations(&self) -> CaptureLocations {
            CaptureLocations(self.0.capture_locations())
        }
    }

    impl RegexBuilder {
        pub fn new(pattern: &str) -> Self {
            Self(regex::RegexBuilder::new(pattern))
        }

        pub fn build(&self) -> Result<Regex, String> {
            self.0.build().map(Regex).map_err(|e| e.to_string())
        }

        pub fn unicode(&mut self, yes: bool) -> &Self {
            let _ = self.0.unicode(yes);
            self
        }

        pub fn case_insensitive(&mut self, yes: bool) -> &Self {
            let _ = self.0.case_insensitive(yes);
            self
        }

        pub fn multi_line(&mut self, yes: bool) -> &Self {
            let _ = self.0.multi_line(yes);
            self
        }

        pub fn dot_matches_new_line(&mut self, yes: bool) -> &Self {
            let _ = self.0.dot_matches_new_line(yes);
            self
        }

        pub fn crlf(&mut self, yes: bool) -> &Self {
            let _ = self.0.crlf(yes);
            self
        }

        pub fn line_terminator(&mut self, byte: u8) -> &Self {
            let _ = self.0.line_terminator(byte);
            self
        }

        pub fn swap_greed(&mut self, yes: bool) -> &Self {
            let _ = self.0.swap_greed(yes);
            self
        }

        pub fn ignore_whitespace(&mut self, yes: bool) -> &Self {
            let _ = self.0.ignore_whitespace(yes);
            self
        }

        pub fn octal(&mut self, yes: bool) -> &Self {
            let _ = self.0.octal(yes);
            self
        }

        pub fn size_limit(&mut self, bytes: usize) -> &Self {
            let _ = self.0.size_limit(bytes);
            self
        }

        pub fn dfa_size_limit(&mut self, bytes: usize) -> &Self {
            let _ = self.0.dfa_size_limit(bytes);
            self
        }

        pub fn nest_limit(&mut self, limit: u32) -> &Self {
            let _ = self.0.nest_limit(limit);
            self
        }
    }

    impl RegexSet {
        pub fn empty() -> Self {
            Self(regex::RegexSet::empty())
        }

        pub fn is_match(&self, haystack: &str) -> bool {
            self.0.is_match(haystack)
        }

        pub fn is_match_at(&self, haystack: &str, start: usize) -> bool {
            self.0.is_match_at(haystack, start)
        }

        pub fn matches(&self, haystack: &str) -> SetMatches {
            SetMatches(self.0.matches(haystack))
        }

        pub fn matches_at(&self, haystack: &str, start: usize) -> SetMatches {
            SetMatches(self.0.matches_at(haystack, start))
        }

        pub fn len(&self) -> usize {
            self.0.len()
        }

        pub fn is_empty(&self) -> bool {
            self.0.is_empty()
        }

        pub fn patterns(&self) -> OwnedPatterns {
            OwnedPatterns::wrap(&self.0)
        }

        #[jac(assoc)]
        pub fn new(exprs: Wide<Vec<String>>) -> Result<Self, String> {
            regex::RegexSet::new(exprs.0).map(Self).map_err(|e| e.to_string())
        }
    }

    impl RegexSetBuilder {
        pub fn new(patterns: Wide<Vec<String>>) -> Self {
            Self(regex::RegexSetBuilder::new(patterns.0))
        }

        pub fn build(&self) -> Result<RegexSet, String> {
            self.0.build().map(RegexSet).map_err(|e| e.to_string())
        }

        pub fn unicode(&mut self, yes: bool) -> &Self {
            let _ = self.0.unicode(yes);
            self
        }

        pub fn case_insensitive(&mut self, yes: bool) -> &Self {
            let _ = self.0.case_insensitive(yes);
            self
        }

        pub fn multi_line(&mut self, yes: bool) -> &Self {
            let _ = self.0.multi_line(yes);
            self
        }

        pub fn dot_matches_new_line(&mut self, yes: bool) -> &Self {
            let _ = self.0.dot_matches_new_line(yes);
            self
        }

        pub fn crlf(&mut self, yes: bool) -> &Self {
            let _ = self.0.crlf(yes);
            self
        }

        pub fn line_terminator(&mut self, byte: u8) -> &Self {
            let _ = self.0.line_terminator(byte);
            self
        }

        pub fn swap_greed(&mut self, yes: bool) -> &Self {
            let _ = self.0.swap_greed(yes);
            self
        }

        pub fn ignore_whitespace(&mut self, yes: bool) -> &Self {
            let _ = self.0.ignore_whitespace(yes);
            self
        }

        pub fn octal(&mut self, yes: bool) -> &Self {
            let _ = self.0.octal(yes);
            self
        }

        pub fn size_limit(&mut self, bytes: usize) -> &Self {
            let _ = self.0.size_limit(bytes);
            self
        }

        pub fn dfa_size_limit(&mut self, bytes: usize) -> &Self {
            let _ = self.0.dfa_size_limit(bytes);
            self
        }

        pub fn nest_limit(&mut self, limit: u32) -> &Self {
            let _ = self.0.nest_limit(limit);
            self
        }
    }

    impl SetMatches {
        pub fn matched_any(&self) -> bool {
            self.0.matched_any()
        }

        pub fn matched_all(&self) -> bool {
            self.0.matched_all()
        }

        pub fn matched(&self, index: usize) -> bool {
            self.0.matched(index)
        }

        pub fn len(&self) -> usize {
            self.0.len()
        }

        pub fn iter(&self) -> Vec<usize> {
            self.0.iter().collect()
        }
    }
}
