// Auto-generated by jac-bridge-binder. Do not edit.
// crate: semver  version: 1.0.27

use jac_bridge::bridge;

#[bridge(module = "semver")]
#[allow(dead_code)]
mod bridge_impl {
    pub struct BuildMetadata(pub semver::BuildMetadata);

    pub struct Comparator(pub semver::Comparator);

    pub struct Prerelease(pub semver::Prerelease);

    pub struct Version(pub semver::Version);

    pub struct VersionReq(pub semver::VersionReq);

    #[jac_error]
    pub struct SemverError;

    impl BuildMetadata {
        pub fn new(text: &str) -> Result<Self, String> {
            semver::BuildMetadata::new(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn as_str(&self) -> String {
            self.0.as_str().to_string()
        }

        pub fn is_empty(&self) -> bool {
            self.0.is_empty()
        }

        pub fn to_string(&self) -> String {
            self.0.to_string()
        }

        pub fn cmp(&self, other: &BuildMetadata) -> i8 {
            match self.0.cmp(&other.0) { ::std::cmp::Ordering::Less => -1i8, ::std::cmp::Ordering::Equal => 0i8, ::std::cmp::Ordering::Greater => 1i8 }
        }

        #[jac(assoc)]
        pub fn from_str(text: &str) -> Result<Self, String> {
            <semver::BuildMetadata as ::std::str::FromStr>::from_str(text).map(Self).map_err(|e| e.to_string())
        }
    }

    impl Comparator {
        pub fn parse(text: &str) -> Result<Self, String> {
            semver::Comparator::parse(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn matches(&self, version: &Version) -> bool {
            self.0.matches(&version.0)
        }

        pub fn to_string(&self) -> String {
            self.0.to_string()
        }

        #[jac(assoc)]
        pub fn from_str(text: &str) -> Result<Self, String> {
            <semver::Comparator as ::std::str::FromStr>::from_str(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn op(&self) -> String {
            match self.0.op { semver::Op::Exact => "Exact", semver::Op::Greater => "Greater", semver::Op::GreaterEq => "GreaterEq", semver::Op::Less => "Less", semver::Op::LessEq => "LessEq", semver::Op::Tilde => "Tilde", semver::Op::Caret => "Caret", semver::Op::Wildcard => "Wildcard", _ => "unknown", }.to_string()
        }

        pub fn major(&self) -> u64 {
            self.0.major
        }

        pub fn minor(&self) -> Option<u64> {
            self.0.minor
        }

        pub fn patch(&self) -> Option<u64> {
            self.0.patch
        }

        pub fn pre(&self) -> Prerelease {
            Prerelease(self.0.pre.clone())
        }
    }

    impl Prerelease {
        pub fn new(text: &str) -> Result<Self, String> {
            semver::Prerelease::new(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn as_str(&self) -> String {
            self.0.as_str().to_string()
        }

        pub fn is_empty(&self) -> bool {
            self.0.is_empty()
        }

        pub fn to_string(&self) -> String {
            self.0.to_string()
        }

        pub fn cmp(&self, other: &Prerelease) -> i8 {
            match self.0.cmp(&other.0) { ::std::cmp::Ordering::Less => -1i8, ::std::cmp::Ordering::Equal => 0i8, ::std::cmp::Ordering::Greater => 1i8 }
        }

        #[jac(assoc)]
        pub fn from_str(text: &str) -> Result<Self, String> {
            <semver::Prerelease as ::std::str::FromStr>::from_str(text).map(Self).map_err(|e| e.to_string())
        }
    }

    impl Version {
        pub fn new(major: u64, minor: u64, patch: u64) -> Self {
            Self(semver::Version::new(major, minor, patch))
        }

        pub fn cmp_precedence(&self, other: &Version) -> i8 {
            match self.0.cmp_precedence(&other.0) { ::std::cmp::Ordering::Less => -1i8, ::std::cmp::Ordering::Equal => 0i8, ::std::cmp::Ordering::Greater => 1i8 }
        }

        #[jac(assoc)]
        pub fn parse(text: &str) -> Result<Self, String> {
            semver::Version::parse(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn to_string(&self) -> String {
            self.0.to_string()
        }

        pub fn cmp(&self, other: &Version) -> i8 {
            match self.0.cmp(&other.0) { ::std::cmp::Ordering::Less => -1i8, ::std::cmp::Ordering::Equal => 0i8, ::std::cmp::Ordering::Greater => 1i8 }
        }

        #[jac(assoc)]
        pub fn from_str(text: &str) -> Result<Self, String> {
            <semver::Version as ::std::str::FromStr>::from_str(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn major(&self) -> u64 {
            self.0.major
        }

        pub fn minor(&self) -> u64 {
            self.0.minor
        }

        pub fn patch(&self) -> u64 {
            self.0.patch
        }

        pub fn pre(&self) -> Prerelease {
            Prerelease(self.0.pre.clone())
        }

        pub fn build(&self) -> BuildMetadata {
            BuildMetadata(self.0.build.clone())
        }
    }

    impl VersionReq {
        pub fn parse(text: &str) -> Result<Self, String> {
            semver::VersionReq::parse(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn matches(&self, version: &Version) -> bool {
            self.0.matches(&version.0)
        }

        pub fn to_string(&self) -> String {
            self.0.to_string()
        }

        #[jac(assoc)]
        pub fn from_str(text: &str) -> Result<Self, String> {
            <semver::VersionReq as ::std::str::FromStr>::from_str(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn comparators(&self) -> Vec<Comparator> {
            self.0.comparators.iter().map(|x| Comparator(x.clone())).collect()
        }
    }
}
