// Auto-generated by jac-bridge-binder. Do not edit.
// crate: semver  version: 1.0.27

use jac_bridge::bridge;

#[bridge(module = "semver")]
#[allow(dead_code)]
mod bridge_impl {
    pub struct BuildMetadata(pub semver::BuildMetadata);

    pub struct Prerelease(pub semver::Prerelease);

    pub struct Version(pub semver::Version);

    pub struct VersionReq(pub semver::VersionReq);

    #[jac_error]
    pub struct SemverError;

    impl BuildMetadata {
        pub fn new(text: &str) -> Result<Self, String> {
            semver::BuildMetadata::new(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn as_str(&self) -> String {
            self.0.as_str().to_string()
        }

        pub fn is_empty(&self) -> bool {
            self.0.is_empty()
        }
    }

    impl Prerelease {
        pub fn new(text: &str) -> Result<Self, String> {
            semver::Prerelease::new(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn as_str(&self) -> String {
            self.0.as_str().to_string()
        }

        pub fn is_empty(&self) -> bool {
            self.0.is_empty()
        }
    }

    impl Version {
        pub fn new(major: u64, minor: u64, patch: u64) -> Self {
            Self(semver::Version::new(major, minor, patch))
        }

        #[jac(assoc)]
        pub fn parse(text: &str) -> Result<Self, String> {
            semver::Version::parse(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn major(&self) -> u64 { self.0.major }
        pub fn minor(&self) -> u64 { self.0.minor }
        pub fn patch(&self) -> u64 { self.0.patch }
        pub fn cmp(&self, other: &Version) -> i8 {
            match self.0.cmp(&other.0) {
                ::std::cmp::Ordering::Less => -1,
                ::std::cmp::Ordering::Equal => 0,
                ::std::cmp::Ordering::Greater => 1,
            }
        }
    }

    impl VersionReq {
        pub fn parse(text: &str) -> Result<Self, String> {
            semver::VersionReq::parse(text).map(Self).map_err(|e| e.to_string())
        }

        pub fn matches(&self, version: &Version) -> bool {
            self.0.matches(&version.0)
        }
    }
}
