/* The configure feature values native Jac modules were generated with.
 *
 * Generated by scripts/jacpython/gen_constants.jac from the FEATURES of
 * each jaclang/runtime/python/modules/<name>_constants.<os>[.<arch>].jac;
 * do not edit. build.sh compiles it against every JacPython build's
 * pyconfig.h, so a table that disagrees with its build fails the build.
 */
#include "pyconfig.h"

#if defined(__APPLE__)
#if HAVE_BROKEN_NICE != 0
#error "HAVE_BROKEN_NICE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_BROKEN_UNSETENV != 0
#error "HAVE_BROKEN_UNSETENV is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_CHFLAGS != 1
#error "HAVE_CHFLAGS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_CHMOD != 1
#error "HAVE_CHMOD is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_CHOWN != 1
#error "HAVE_CHOWN is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_CHROOT != 1
#error "HAVE_CHROOT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_CONFSTR != 1
#error "HAVE_CONFSTR is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_COPY_FILE_RANGE != 0
#error "HAVE_COPY_FILE_RANGE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_CTERMID != 1
#error "HAVE_CTERMID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_CTERMID_R != 1
#error "HAVE_CTERMID_R is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DECL_RTLD_DEEPBIND != 0
#error "HAVE_DECL_RTLD_DEEPBIND is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_DECL_RTLD_GLOBAL != 1
#error "HAVE_DECL_RTLD_GLOBAL is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DECL_RTLD_LAZY != 1
#error "HAVE_DECL_RTLD_LAZY is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DECL_RTLD_LOCAL != 1
#error "HAVE_DECL_RTLD_LOCAL is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DECL_RTLD_MEMBER != 0
#error "HAVE_DECL_RTLD_MEMBER is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_DECL_RTLD_NODELETE != 1
#error "HAVE_DECL_RTLD_NODELETE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DECL_RTLD_NOLOAD != 1
#error "HAVE_DECL_RTLD_NOLOAD is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DECL_RTLD_NOW != 1
#error "HAVE_DECL_RTLD_NOW is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DEVICE_MACROS != 1
#error "HAVE_DEVICE_MACROS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DEV_PTC != 0
#error "HAVE_DEV_PTC is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_DEV_PTMX != 1
#error "HAVE_DEV_PTMX is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DIRECT_H != 0
#error "HAVE_DIRECT_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_DIRENT_D_TYPE != 1
#error "HAVE_DIRENT_D_TYPE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DIRENT_H != 1
#error "HAVE_DIRENT_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DLFCN_H != 1
#error "HAVE_DLFCN_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_DUP3 != 0
#error "HAVE_DUP3 is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_EVENTFD != 0
#error "HAVE_EVENTFD is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_EXECV != 1
#error "HAVE_EXECV is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FACCESSAT != 1
#error "HAVE_FACCESSAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FCHDIR != 1
#error "HAVE_FCHDIR is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FCHMOD != 1
#error "HAVE_FCHMOD is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FCHMODAT != 1
#error "HAVE_FCHMODAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FCHOWN != 1
#error "HAVE_FCHOWN is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FCHOWNAT != 1
#error "HAVE_FCHOWNAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FCNTL_H != 1
#error "HAVE_FCNTL_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FDATASYNC != 0
#error "HAVE_FDATASYNC is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_FDOPENDIR != 1
#error "HAVE_FDOPENDIR is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FEXECVE != 0
#error "HAVE_FEXECVE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_FORK != 1
#error "HAVE_FORK is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FORK1 != 0
#error "HAVE_FORK1 is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_FORKPTY != 1
#error "HAVE_FORKPTY is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FPATHCONF != 1
#error "HAVE_FPATHCONF is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FSTATAT != 1
#error "HAVE_FSTATAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FSTATVFS != 1
#error "HAVE_FSTATVFS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FSYNC != 1
#error "HAVE_FSYNC is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FTRUNCATE != 1
#error "HAVE_FTRUNCATE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FUTIMENS != 1
#error "HAVE_FUTIMENS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FUTIMES != 1
#error "HAVE_FUTIMES is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_FUTIMESAT != 0
#error "HAVE_FUTIMESAT is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETEGID != 1
#error "HAVE_GETEGID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETEUID != 1
#error "HAVE_GETEUID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETGID != 1
#error "HAVE_GETGID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETGROUPLIST != 1
#error "HAVE_GETGROUPLIST is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETGROUPS != 1
#error "HAVE_GETGROUPS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETLOADAVG != 1
#error "HAVE_GETLOADAVG is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETLOGIN != 1
#error "HAVE_GETLOGIN is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETLOGIN_R != 1
#error "HAVE_GETLOGIN_R is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETPGID != 1
#error "HAVE_GETPGID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETPGRP != 1
#error "HAVE_GETPGRP is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETPID != 1
#error "HAVE_GETPID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETPPID != 1
#error "HAVE_GETPPID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETPRIORITY != 1
#error "HAVE_GETPRIORITY is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETRANDOM_SYSCALL != 0
#error "HAVE_GETRANDOM_SYSCALL is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETRESGID != 0
#error "HAVE_GETRESGID is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETRESUID != 0
#error "HAVE_GETRESUID is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETSID != 1
#error "HAVE_GETSID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GETUID != 1
#error "HAVE_GETUID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GRANTPT != 1
#error "HAVE_GRANTPT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_GRP_H != 1
#error "HAVE_GRP_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_INITGROUPS != 1
#error "HAVE_INITGROUPS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_IO_H != 0
#error "HAVE_IO_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_KILL != 1
#error "HAVE_KILL is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_KILLPG != 1
#error "HAVE_KILLPG is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LARGEFILE_SUPPORT != 0
#error "HAVE_LARGEFILE_SUPPORT is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_LCHFLAGS != 1
#error "HAVE_LCHFLAGS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LCHMOD != 1
#error "HAVE_LCHMOD is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LCHOWN != 1
#error "HAVE_LCHOWN is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LIBUTIL_H != 0
#error "HAVE_LIBUTIL_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_LINK != 1
#error "HAVE_LINK is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LINKAT != 1
#error "HAVE_LINKAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LINUX_LIMITS_H != 0
#error "HAVE_LINUX_LIMITS_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_LINUX_MEMFD_H != 0
#error "HAVE_LINUX_MEMFD_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_LINUX_RANDOM_H != 0
#error "HAVE_LINUX_RANDOM_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_LINUX_SCHED_H != 0
#error "HAVE_LINUX_SCHED_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_LINUX_WAIT_H != 0
#error "HAVE_LINUX_WAIT_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_LOCKF != 1
#error "HAVE_LOCKF is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LOGIN_TTY != 1
#error "HAVE_LOGIN_TTY is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LSTAT != 1
#error "HAVE_LSTAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_LUTIMES != 1
#error "HAVE_LUTIMES is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_MAKEDEV != 1
#error "HAVE_MAKEDEV is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_MAXLOGNAME != 1
#error "HAVE_MAXLOGNAME is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_MEMFD_CREATE != 0
#error "HAVE_MEMFD_CREATE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_MKDIRAT != 1
#error "HAVE_MKDIRAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_MKFIFO != 1
#error "HAVE_MKFIFO is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_MKFIFOAT != 1
#error "HAVE_MKFIFOAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_MKNOD != 1
#error "HAVE_MKNOD is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_MKNODAT != 1
#error "HAVE_MKNODAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_NDIR_H != 0
#error "HAVE_NDIR_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_NICE != 1
#error "HAVE_NICE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_OPENAT != 1
#error "HAVE_OPENAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_OPENDIR != 1
#error "HAVE_OPENDIR is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_OPENPTY != 1
#error "HAVE_OPENPTY is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PATHCONF != 1
#error "HAVE_PATHCONF is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PIPE != 1
#error "HAVE_PIPE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PIPE2 != 0
#error "HAVE_PIPE2 is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_PLOCK != 0
#error "HAVE_PLOCK is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_POSIX_FADVISE != 0
#error "HAVE_POSIX_FADVISE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_POSIX_FALLOCATE != 0
#error "HAVE_POSIX_FALLOCATE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_POSIX_OPENPT != 1
#error "HAVE_POSIX_OPENPT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_POSIX_SPAWN != 1
#error "HAVE_POSIX_SPAWN is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_POSIX_SPAWNP != 1
#error "HAVE_POSIX_SPAWNP is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PREAD != 1
#error "HAVE_PREAD is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PREADV != 1
#error "HAVE_PREADV is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PREADV2 != 0
#error "HAVE_PREADV2 is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_PROCESS_H != 0
#error "HAVE_PROCESS_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_PTSNAME != 1
#error "HAVE_PTSNAME is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PTSNAME_R != 1
#error "HAVE_PTSNAME_R is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PTY_H != 0
#error "HAVE_PTY_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_PWRITE != 1
#error "HAVE_PWRITE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PWRITEV != 1
#error "HAVE_PWRITEV is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_PWRITEV2 != 0
#error "HAVE_PWRITEV2 is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_READLINK != 1
#error "HAVE_READLINK is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_READLINKAT != 1
#error "HAVE_READLINKAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_READV != 1
#error "HAVE_READV is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_RENAMEAT != 1
#error "HAVE_RENAMEAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_RTPSPAWN != 0
#error "HAVE_RTPSPAWN is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SCHED_GET_PRIORITY_MAX != 1
#error "HAVE_SCHED_GET_PRIORITY_MAX is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SCHED_H != 1
#error "HAVE_SCHED_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SCHED_RR_GET_INTERVAL != 0
#error "HAVE_SCHED_RR_GET_INTERVAL is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SCHED_SETAFFINITY != 0
#error "HAVE_SCHED_SETAFFINITY is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SCHED_SETPARAM != 0
#error "HAVE_SCHED_SETPARAM is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SCHED_SETSCHEDULER != 0
#error "HAVE_SCHED_SETSCHEDULER is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SENDFILE != 1
#error "HAVE_SENDFILE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETEGID != 1
#error "HAVE_SETEGID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETEUID != 1
#error "HAVE_SETEUID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETGID != 1
#error "HAVE_SETGID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETGROUPS != 1
#error "HAVE_SETGROUPS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETNS != 0
#error "HAVE_SETNS is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETPGID != 1
#error "HAVE_SETPGID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETPGRP != 1
#error "HAVE_SETPGRP is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETPRIORITY != 1
#error "HAVE_SETPRIORITY is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETREGID != 1
#error "HAVE_SETREGID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETRESGID != 0
#error "HAVE_SETRESGID is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETRESUID != 0
#error "HAVE_SETRESUID is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETREUID != 1
#error "HAVE_SETREUID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETSID != 1
#error "HAVE_SETSID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SETUID != 1
#error "HAVE_SETUID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SIGNAL_H != 1
#error "HAVE_SIGNAL_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SPLICE != 0
#error "HAVE_SPLICE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_STATVFS != 1
#error "HAVE_STATVFS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_STAT_TV_NSEC != 0
#error "HAVE_STAT_TV_NSEC is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_STAT_TV_NSEC2 != 1
#error "HAVE_STAT_TV_NSEC2 is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_STROPTS_H != 0
#error "HAVE_STROPTS_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BIRTHTIME != 1
#error "HAVE_STRUCT_STAT_ST_BIRTHTIME is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BLKSIZE != 1
#error "HAVE_STRUCT_STAT_ST_BLKSIZE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BLOCKS != 1
#error "HAVE_STRUCT_STAT_ST_BLOCKS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_FLAGS != 1
#error "HAVE_STRUCT_STAT_ST_FLAGS is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_GEN != 1
#error "HAVE_STRUCT_STAT_ST_GEN is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_RDEV != 1
#error "HAVE_STRUCT_STAT_ST_RDEV is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYMLINK != 1
#error "HAVE_SYMLINK is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYMLINKAT != 1
#error "HAVE_SYMLINKAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYNC != 1
#error "HAVE_SYNC is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYSCONF != 1
#error "HAVE_SYSCONF is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYSEXITS_H != 1
#error "HAVE_SYSEXITS_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYSTEM != 1
#error "HAVE_SYSTEM is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_DIR_H != 0
#error "HAVE_SYS_DIR_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_EVENTFD_H != 0
#error "HAVE_SYS_EVENTFD_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_IOCTL_H != 1
#error "HAVE_SYS_IOCTL_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_LOADAVG_H != 0
#error "HAVE_SYS_LOADAVG_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_LOCK_H != 1
#error "HAVE_SYS_LOCK_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_MEMFD_H != 0
#error "HAVE_SYS_MEMFD_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_MKDEV_H != 0
#error "HAVE_SYS_MKDEV_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_MMAN_H != 1
#error "HAVE_SYS_MMAN_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_NDIR_H != 0
#error "HAVE_SYS_NDIR_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_PARAM_H != 1
#error "HAVE_SYS_PARAM_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_PIDFD_H != 0
#error "HAVE_SYS_PIDFD_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_RESOURCE_H != 1
#error "HAVE_SYS_RESOURCE_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_SENDFILE_H != 0
#error "HAVE_SYS_SENDFILE_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_SOCKET_H != 1
#error "HAVE_SYS_SOCKET_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_STATVFS_H != 1
#error "HAVE_SYS_STATVFS_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_STAT_H != 1
#error "HAVE_SYS_STAT_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_SYSMACROS_H != 0
#error "HAVE_SYS_SYSMACROS_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_TIMERFD_H != 0
#error "HAVE_SYS_TIMERFD_H is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_TIMES_H != 1
#error "HAVE_SYS_TIMES_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_TIME_H != 1
#error "HAVE_SYS_TIME_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_TYPES_H != 1
#error "HAVE_SYS_TYPES_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_UIO_H != 1
#error "HAVE_SYS_UIO_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_UTSNAME_H != 1
#error "HAVE_SYS_UTSNAME_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_WAIT_H != 1
#error "HAVE_SYS_WAIT_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_SYS_XATTR_H != 1
#error "HAVE_SYS_XATTR_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_TCGETPGRP != 1
#error "HAVE_TCGETPGRP is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_TCSETPGRP != 1
#error "HAVE_TCSETPGRP is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_TERMIOS_H != 1
#error "HAVE_TERMIOS_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_TIMERFD_CREATE != 0
#error "HAVE_TIMERFD_CREATE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_TRUNCATE != 1
#error "HAVE_TRUNCATE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_TTYNAME_R != 1
#error "HAVE_TTYNAME_R is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UMASK != 1
#error "HAVE_UMASK is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UNAME != 1
#error "HAVE_UNAME is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UNISTD_H != 1
#error "HAVE_UNISTD_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UNLINKAT != 1
#error "HAVE_UNLINKAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UNLOCKPT != 1
#error "HAVE_UNLOCKPT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UNSHARE != 0
#error "HAVE_UNSHARE is not 0 as posix_constants.darwin.jac records"
#endif
#if HAVE_UTIL_H != 1
#error "HAVE_UTIL_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UTIMENSAT != 1
#error "HAVE_UTIMENSAT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UTIMES != 1
#error "HAVE_UTIMES is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UTIME_H != 1
#error "HAVE_UTIME_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UTMP_H != 1
#error "HAVE_UTMP_H is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_UT_NAMESIZE != 1
#error "HAVE_UT_NAMESIZE is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_WAIT != 1
#error "HAVE_WAIT is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_WAIT3 != 1
#error "HAVE_WAIT3 is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_WAIT4 != 1
#error "HAVE_WAIT4 is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_WAITID != 1
#error "HAVE_WAITID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_WAITPID != 1
#error "HAVE_WAITPID is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE_WRITEV != 1
#error "HAVE_WRITEV is not 1 as posix_constants.darwin.jac records"
#endif
#if HAVE__GETPTY != 0
#error "HAVE__GETPTY is not 0 as posix_constants.darwin.jac records"
#endif
#endif

#if defined(__linux__) && defined(__aarch64__)
#if HAVE_BROKEN_NICE != 0
#error "HAVE_BROKEN_NICE is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_BROKEN_UNSETENV != 0
#error "HAVE_BROKEN_UNSETENV is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_CHFLAGS != 0
#error "HAVE_CHFLAGS is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_CHMOD != 1
#error "HAVE_CHMOD is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_CHOWN != 1
#error "HAVE_CHOWN is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_CHROOT != 1
#error "HAVE_CHROOT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_CONFSTR != 1
#error "HAVE_CONFSTR is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_COPY_FILE_RANGE != 0
#error "HAVE_COPY_FILE_RANGE is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_CTERMID != 1
#error "HAVE_CTERMID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_CTERMID_R != 0
#error "HAVE_CTERMID_R is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DECL_RTLD_DEEPBIND != 1
#error "HAVE_DECL_RTLD_DEEPBIND is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DECL_RTLD_GLOBAL != 1
#error "HAVE_DECL_RTLD_GLOBAL is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DECL_RTLD_LAZY != 1
#error "HAVE_DECL_RTLD_LAZY is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DECL_RTLD_LOCAL != 1
#error "HAVE_DECL_RTLD_LOCAL is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DECL_RTLD_MEMBER != 0
#error "HAVE_DECL_RTLD_MEMBER is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DECL_RTLD_NODELETE != 1
#error "HAVE_DECL_RTLD_NODELETE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DECL_RTLD_NOLOAD != 1
#error "HAVE_DECL_RTLD_NOLOAD is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DECL_RTLD_NOW != 1
#error "HAVE_DECL_RTLD_NOW is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DEVICE_MACROS != 1
#error "HAVE_DEVICE_MACROS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DEV_PTC != 0
#error "HAVE_DEV_PTC is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DEV_PTMX != 1
#error "HAVE_DEV_PTMX is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DIRECT_H != 0
#error "HAVE_DIRECT_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DIRENT_D_TYPE != 1
#error "HAVE_DIRENT_D_TYPE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DIRENT_H != 1
#error "HAVE_DIRENT_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DLFCN_H != 1
#error "HAVE_DLFCN_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_DUP3 != 1
#error "HAVE_DUP3 is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_EVENTFD != 1
#error "HAVE_EVENTFD is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_EXECV != 1
#error "HAVE_EXECV is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FACCESSAT != 1
#error "HAVE_FACCESSAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FCHDIR != 1
#error "HAVE_FCHDIR is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FCHMOD != 1
#error "HAVE_FCHMOD is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FCHMODAT != 1
#error "HAVE_FCHMODAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FCHOWN != 1
#error "HAVE_FCHOWN is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FCHOWNAT != 1
#error "HAVE_FCHOWNAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FCNTL_H != 1
#error "HAVE_FCNTL_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FDATASYNC != 1
#error "HAVE_FDATASYNC is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FDOPENDIR != 1
#error "HAVE_FDOPENDIR is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FEXECVE != 1
#error "HAVE_FEXECVE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FORK != 1
#error "HAVE_FORK is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FORK1 != 0
#error "HAVE_FORK1 is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FORKPTY != 1
#error "HAVE_FORKPTY is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FPATHCONF != 1
#error "HAVE_FPATHCONF is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FSTATAT != 1
#error "HAVE_FSTATAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FSTATVFS != 1
#error "HAVE_FSTATVFS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FSYNC != 1
#error "HAVE_FSYNC is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FTRUNCATE != 1
#error "HAVE_FTRUNCATE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FUTIMENS != 1
#error "HAVE_FUTIMENS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FUTIMES != 1
#error "HAVE_FUTIMES is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_FUTIMESAT != 1
#error "HAVE_FUTIMESAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETEGID != 1
#error "HAVE_GETEGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETEUID != 1
#error "HAVE_GETEUID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETGID != 1
#error "HAVE_GETGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETGROUPLIST != 1
#error "HAVE_GETGROUPLIST is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETGROUPS != 1
#error "HAVE_GETGROUPS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETLOADAVG != 1
#error "HAVE_GETLOADAVG is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETLOGIN != 1
#error "HAVE_GETLOGIN is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETLOGIN_R != 1
#error "HAVE_GETLOGIN_R is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETPGID != 1
#error "HAVE_GETPGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETPGRP != 1
#error "HAVE_GETPGRP is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETPID != 1
#error "HAVE_GETPID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETPPID != 1
#error "HAVE_GETPPID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETPRIORITY != 1
#error "HAVE_GETPRIORITY is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETRANDOM_SYSCALL != 1
#error "HAVE_GETRANDOM_SYSCALL is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETRESGID != 1
#error "HAVE_GETRESGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETRESUID != 1
#error "HAVE_GETRESUID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETSID != 1
#error "HAVE_GETSID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GETUID != 1
#error "HAVE_GETUID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GRANTPT != 1
#error "HAVE_GRANTPT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_GRP_H != 1
#error "HAVE_GRP_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_INITGROUPS != 1
#error "HAVE_INITGROUPS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_IO_H != 0
#error "HAVE_IO_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_KILL != 1
#error "HAVE_KILL is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_KILLPG != 1
#error "HAVE_KILLPG is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LARGEFILE_SUPPORT != 0
#error "HAVE_LARGEFILE_SUPPORT is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LCHFLAGS != 0
#error "HAVE_LCHFLAGS is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LCHMOD != 0
#error "HAVE_LCHMOD is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LCHOWN != 1
#error "HAVE_LCHOWN is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LIBUTIL_H != 0
#error "HAVE_LIBUTIL_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LINK != 1
#error "HAVE_LINK is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LINKAT != 1
#error "HAVE_LINKAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LINUX_LIMITS_H != 1
#error "HAVE_LINUX_LIMITS_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LINUX_MEMFD_H != 1
#error "HAVE_LINUX_MEMFD_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LINUX_RANDOM_H != 1
#error "HAVE_LINUX_RANDOM_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LINUX_SCHED_H != 1
#error "HAVE_LINUX_SCHED_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LINUX_WAIT_H != 1
#error "HAVE_LINUX_WAIT_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LOCKF != 1
#error "HAVE_LOCKF is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LOGIN_TTY != 1
#error "HAVE_LOGIN_TTY is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LSTAT != 1
#error "HAVE_LSTAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_LUTIMES != 1
#error "HAVE_LUTIMES is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_MAKEDEV != 1
#error "HAVE_MAKEDEV is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_MAXLOGNAME != 0
#error "HAVE_MAXLOGNAME is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_MEMFD_CREATE != 0
#error "HAVE_MEMFD_CREATE is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_MKDIRAT != 1
#error "HAVE_MKDIRAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_MKFIFO != 1
#error "HAVE_MKFIFO is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_MKFIFOAT != 1
#error "HAVE_MKFIFOAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_MKNOD != 1
#error "HAVE_MKNOD is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_MKNODAT != 1
#error "HAVE_MKNODAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_NDIR_H != 0
#error "HAVE_NDIR_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_NICE != 1
#error "HAVE_NICE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_OPENAT != 1
#error "HAVE_OPENAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_OPENDIR != 1
#error "HAVE_OPENDIR is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_OPENPTY != 1
#error "HAVE_OPENPTY is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PATHCONF != 1
#error "HAVE_PATHCONF is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PIPE != 1
#error "HAVE_PIPE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PIPE2 != 1
#error "HAVE_PIPE2 is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PLOCK != 0
#error "HAVE_PLOCK is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_POSIX_FADVISE != 1
#error "HAVE_POSIX_FADVISE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_POSIX_FALLOCATE != 1
#error "HAVE_POSIX_FALLOCATE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_POSIX_OPENPT != 1
#error "HAVE_POSIX_OPENPT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_POSIX_SPAWN != 1
#error "HAVE_POSIX_SPAWN is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_POSIX_SPAWNP != 1
#error "HAVE_POSIX_SPAWNP is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PREAD != 1
#error "HAVE_PREAD is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PREADV != 1
#error "HAVE_PREADV is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PREADV2 != 0
#error "HAVE_PREADV2 is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PROCESS_H != 0
#error "HAVE_PROCESS_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PTSNAME != 1
#error "HAVE_PTSNAME is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PTSNAME_R != 1
#error "HAVE_PTSNAME_R is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PTY_H != 1
#error "HAVE_PTY_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PWRITE != 1
#error "HAVE_PWRITE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PWRITEV != 1
#error "HAVE_PWRITEV is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_PWRITEV2 != 0
#error "HAVE_PWRITEV2 is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_READLINK != 1
#error "HAVE_READLINK is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_READLINKAT != 1
#error "HAVE_READLINKAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_READV != 1
#error "HAVE_READV is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_RENAMEAT != 1
#error "HAVE_RENAMEAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_RTPSPAWN != 0
#error "HAVE_RTPSPAWN is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SCHED_GET_PRIORITY_MAX != 1
#error "HAVE_SCHED_GET_PRIORITY_MAX is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SCHED_H != 1
#error "HAVE_SCHED_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SCHED_RR_GET_INTERVAL != 1
#error "HAVE_SCHED_RR_GET_INTERVAL is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SCHED_SETAFFINITY != 1
#error "HAVE_SCHED_SETAFFINITY is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SCHED_SETPARAM != 1
#error "HAVE_SCHED_SETPARAM is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SCHED_SETSCHEDULER != 1
#error "HAVE_SCHED_SETSCHEDULER is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SENDFILE != 1
#error "HAVE_SENDFILE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETEGID != 1
#error "HAVE_SETEGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETEUID != 1
#error "HAVE_SETEUID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETGID != 1
#error "HAVE_SETGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETGROUPS != 1
#error "HAVE_SETGROUPS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETNS != 1
#error "HAVE_SETNS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETPGID != 1
#error "HAVE_SETPGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETPGRP != 1
#error "HAVE_SETPGRP is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETPRIORITY != 1
#error "HAVE_SETPRIORITY is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETREGID != 1
#error "HAVE_SETREGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETRESGID != 1
#error "HAVE_SETRESGID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETRESUID != 1
#error "HAVE_SETRESUID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETREUID != 1
#error "HAVE_SETREUID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETSID != 1
#error "HAVE_SETSID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SETUID != 1
#error "HAVE_SETUID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SIGNAL_H != 1
#error "HAVE_SIGNAL_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SPLICE != 1
#error "HAVE_SPLICE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STATVFS != 1
#error "HAVE_STATVFS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STAT_TV_NSEC != 1
#error "HAVE_STAT_TV_NSEC is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STAT_TV_NSEC2 != 0
#error "HAVE_STAT_TV_NSEC2 is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STROPTS_H != 0
#error "HAVE_STROPTS_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BIRTHTIME != 0
#error "HAVE_STRUCT_STAT_ST_BIRTHTIME is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BLKSIZE != 1
#error "HAVE_STRUCT_STAT_ST_BLKSIZE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BLOCKS != 1
#error "HAVE_STRUCT_STAT_ST_BLOCKS is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_FLAGS != 0
#error "HAVE_STRUCT_STAT_ST_FLAGS is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_GEN != 0
#error "HAVE_STRUCT_STAT_ST_GEN is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_RDEV != 1
#error "HAVE_STRUCT_STAT_ST_RDEV is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYMLINK != 1
#error "HAVE_SYMLINK is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYMLINKAT != 1
#error "HAVE_SYMLINKAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYNC != 1
#error "HAVE_SYNC is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYSCONF != 1
#error "HAVE_SYSCONF is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYSEXITS_H != 1
#error "HAVE_SYSEXITS_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYSTEM != 1
#error "HAVE_SYSTEM is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_DIR_H != 0
#error "HAVE_SYS_DIR_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_EVENTFD_H != 1
#error "HAVE_SYS_EVENTFD_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_IOCTL_H != 1
#error "HAVE_SYS_IOCTL_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_LOADAVG_H != 0
#error "HAVE_SYS_LOADAVG_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_LOCK_H != 0
#error "HAVE_SYS_LOCK_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_MEMFD_H != 0
#error "HAVE_SYS_MEMFD_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_MKDEV_H != 0
#error "HAVE_SYS_MKDEV_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_MMAN_H != 1
#error "HAVE_SYS_MMAN_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_NDIR_H != 0
#error "HAVE_SYS_NDIR_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_PARAM_H != 1
#error "HAVE_SYS_PARAM_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_PIDFD_H != 1
#error "HAVE_SYS_PIDFD_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_RESOURCE_H != 1
#error "HAVE_SYS_RESOURCE_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_SENDFILE_H != 1
#error "HAVE_SYS_SENDFILE_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_SOCKET_H != 1
#error "HAVE_SYS_SOCKET_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_STATVFS_H != 1
#error "HAVE_SYS_STATVFS_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_STAT_H != 1
#error "HAVE_SYS_STAT_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_SYSMACROS_H != 1
#error "HAVE_SYS_SYSMACROS_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_TIMERFD_H != 1
#error "HAVE_SYS_TIMERFD_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_TIMES_H != 1
#error "HAVE_SYS_TIMES_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_TIME_H != 1
#error "HAVE_SYS_TIME_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_TYPES_H != 1
#error "HAVE_SYS_TYPES_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_UIO_H != 1
#error "HAVE_SYS_UIO_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_UTSNAME_H != 1
#error "HAVE_SYS_UTSNAME_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_WAIT_H != 1
#error "HAVE_SYS_WAIT_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_SYS_XATTR_H != 1
#error "HAVE_SYS_XATTR_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_TCGETPGRP != 1
#error "HAVE_TCGETPGRP is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_TCSETPGRP != 1
#error "HAVE_TCSETPGRP is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_TERMIOS_H != 1
#error "HAVE_TERMIOS_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_TIMERFD_CREATE != 1
#error "HAVE_TIMERFD_CREATE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_TRUNCATE != 1
#error "HAVE_TRUNCATE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_TTYNAME_R != 1
#error "HAVE_TTYNAME_R is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UMASK != 1
#error "HAVE_UMASK is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UNAME != 1
#error "HAVE_UNAME is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UNISTD_H != 1
#error "HAVE_UNISTD_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UNLINKAT != 1
#error "HAVE_UNLINKAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UNLOCKPT != 1
#error "HAVE_UNLOCKPT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UNSHARE != 1
#error "HAVE_UNSHARE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UTIL_H != 0
#error "HAVE_UTIL_H is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UTIMENSAT != 1
#error "HAVE_UTIMENSAT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UTIMES != 1
#error "HAVE_UTIMES is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UTIME_H != 1
#error "HAVE_UTIME_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UTMP_H != 1
#error "HAVE_UTMP_H is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_UT_NAMESIZE != 1
#error "HAVE_UT_NAMESIZE is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_WAIT != 1
#error "HAVE_WAIT is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_WAIT3 != 1
#error "HAVE_WAIT3 is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_WAIT4 != 1
#error "HAVE_WAIT4 is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_WAITID != 1
#error "HAVE_WAITID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_WAITPID != 1
#error "HAVE_WAITPID is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE_WRITEV != 1
#error "HAVE_WRITEV is not 1 as posix_constants.linux.aarch64.jac records"
#endif
#if HAVE__GETPTY != 0
#error "HAVE__GETPTY is not 0 as posix_constants.linux.aarch64.jac records"
#endif
#endif

#if defined(__linux__) && defined(__x86_64__)
#if HAVE_BROKEN_NICE != 0
#error "HAVE_BROKEN_NICE is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_BROKEN_UNSETENV != 0
#error "HAVE_BROKEN_UNSETENV is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_CHFLAGS != 0
#error "HAVE_CHFLAGS is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_CHMOD != 1
#error "HAVE_CHMOD is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_CHOWN != 1
#error "HAVE_CHOWN is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_CHROOT != 1
#error "HAVE_CHROOT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_CONFSTR != 1
#error "HAVE_CONFSTR is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_COPY_FILE_RANGE != 0
#error "HAVE_COPY_FILE_RANGE is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_CTERMID != 1
#error "HAVE_CTERMID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_CTERMID_R != 0
#error "HAVE_CTERMID_R is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DECL_RTLD_DEEPBIND != 1
#error "HAVE_DECL_RTLD_DEEPBIND is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DECL_RTLD_GLOBAL != 1
#error "HAVE_DECL_RTLD_GLOBAL is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DECL_RTLD_LAZY != 1
#error "HAVE_DECL_RTLD_LAZY is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DECL_RTLD_LOCAL != 1
#error "HAVE_DECL_RTLD_LOCAL is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DECL_RTLD_MEMBER != 0
#error "HAVE_DECL_RTLD_MEMBER is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DECL_RTLD_NODELETE != 1
#error "HAVE_DECL_RTLD_NODELETE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DECL_RTLD_NOLOAD != 1
#error "HAVE_DECL_RTLD_NOLOAD is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DECL_RTLD_NOW != 1
#error "HAVE_DECL_RTLD_NOW is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DEVICE_MACROS != 1
#error "HAVE_DEVICE_MACROS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DEV_PTC != 0
#error "HAVE_DEV_PTC is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DEV_PTMX != 1
#error "HAVE_DEV_PTMX is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DIRECT_H != 0
#error "HAVE_DIRECT_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DIRENT_D_TYPE != 1
#error "HAVE_DIRENT_D_TYPE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DIRENT_H != 1
#error "HAVE_DIRENT_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DLFCN_H != 1
#error "HAVE_DLFCN_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_DUP3 != 1
#error "HAVE_DUP3 is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_EVENTFD != 1
#error "HAVE_EVENTFD is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_EXECV != 1
#error "HAVE_EXECV is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FACCESSAT != 1
#error "HAVE_FACCESSAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FCHDIR != 1
#error "HAVE_FCHDIR is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FCHMOD != 1
#error "HAVE_FCHMOD is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FCHMODAT != 1
#error "HAVE_FCHMODAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FCHOWN != 1
#error "HAVE_FCHOWN is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FCHOWNAT != 1
#error "HAVE_FCHOWNAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FCNTL_H != 1
#error "HAVE_FCNTL_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FDATASYNC != 1
#error "HAVE_FDATASYNC is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FDOPENDIR != 1
#error "HAVE_FDOPENDIR is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FEXECVE != 1
#error "HAVE_FEXECVE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FORK != 1
#error "HAVE_FORK is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FORK1 != 0
#error "HAVE_FORK1 is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FORKPTY != 1
#error "HAVE_FORKPTY is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FPATHCONF != 1
#error "HAVE_FPATHCONF is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FSTATAT != 1
#error "HAVE_FSTATAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FSTATVFS != 1
#error "HAVE_FSTATVFS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FSYNC != 1
#error "HAVE_FSYNC is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FTRUNCATE != 1
#error "HAVE_FTRUNCATE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FUTIMENS != 1
#error "HAVE_FUTIMENS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FUTIMES != 1
#error "HAVE_FUTIMES is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_FUTIMESAT != 1
#error "HAVE_FUTIMESAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETEGID != 1
#error "HAVE_GETEGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETEUID != 1
#error "HAVE_GETEUID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETGID != 1
#error "HAVE_GETGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETGROUPLIST != 1
#error "HAVE_GETGROUPLIST is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETGROUPS != 1
#error "HAVE_GETGROUPS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETLOADAVG != 1
#error "HAVE_GETLOADAVG is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETLOGIN != 1
#error "HAVE_GETLOGIN is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETLOGIN_R != 1
#error "HAVE_GETLOGIN_R is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETPGID != 1
#error "HAVE_GETPGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETPGRP != 1
#error "HAVE_GETPGRP is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETPID != 1
#error "HAVE_GETPID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETPPID != 1
#error "HAVE_GETPPID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETPRIORITY != 1
#error "HAVE_GETPRIORITY is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETRANDOM_SYSCALL != 1
#error "HAVE_GETRANDOM_SYSCALL is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETRESGID != 1
#error "HAVE_GETRESGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETRESUID != 1
#error "HAVE_GETRESUID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETSID != 1
#error "HAVE_GETSID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GETUID != 1
#error "HAVE_GETUID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GRANTPT != 1
#error "HAVE_GRANTPT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_GRP_H != 1
#error "HAVE_GRP_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_INITGROUPS != 1
#error "HAVE_INITGROUPS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_IO_H != 0
#error "HAVE_IO_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_KILL != 1
#error "HAVE_KILL is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_KILLPG != 1
#error "HAVE_KILLPG is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LARGEFILE_SUPPORT != 0
#error "HAVE_LARGEFILE_SUPPORT is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LCHFLAGS != 0
#error "HAVE_LCHFLAGS is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LCHMOD != 0
#error "HAVE_LCHMOD is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LCHOWN != 1
#error "HAVE_LCHOWN is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LIBUTIL_H != 0
#error "HAVE_LIBUTIL_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LINK != 1
#error "HAVE_LINK is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LINKAT != 1
#error "HAVE_LINKAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LINUX_LIMITS_H != 1
#error "HAVE_LINUX_LIMITS_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LINUX_MEMFD_H != 1
#error "HAVE_LINUX_MEMFD_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LINUX_RANDOM_H != 1
#error "HAVE_LINUX_RANDOM_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LINUX_SCHED_H != 1
#error "HAVE_LINUX_SCHED_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LINUX_WAIT_H != 1
#error "HAVE_LINUX_WAIT_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LOCKF != 1
#error "HAVE_LOCKF is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LOGIN_TTY != 1
#error "HAVE_LOGIN_TTY is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LSTAT != 1
#error "HAVE_LSTAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_LUTIMES != 1
#error "HAVE_LUTIMES is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_MAKEDEV != 1
#error "HAVE_MAKEDEV is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_MAXLOGNAME != 0
#error "HAVE_MAXLOGNAME is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_MEMFD_CREATE != 0
#error "HAVE_MEMFD_CREATE is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_MKDIRAT != 1
#error "HAVE_MKDIRAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_MKFIFO != 1
#error "HAVE_MKFIFO is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_MKFIFOAT != 1
#error "HAVE_MKFIFOAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_MKNOD != 1
#error "HAVE_MKNOD is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_MKNODAT != 1
#error "HAVE_MKNODAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_NDIR_H != 0
#error "HAVE_NDIR_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_NICE != 1
#error "HAVE_NICE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_OPENAT != 1
#error "HAVE_OPENAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_OPENDIR != 1
#error "HAVE_OPENDIR is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_OPENPTY != 1
#error "HAVE_OPENPTY is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PATHCONF != 1
#error "HAVE_PATHCONF is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PIPE != 1
#error "HAVE_PIPE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PIPE2 != 1
#error "HAVE_PIPE2 is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PLOCK != 0
#error "HAVE_PLOCK is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_POSIX_FADVISE != 1
#error "HAVE_POSIX_FADVISE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_POSIX_FALLOCATE != 1
#error "HAVE_POSIX_FALLOCATE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_POSIX_OPENPT != 1
#error "HAVE_POSIX_OPENPT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_POSIX_SPAWN != 1
#error "HAVE_POSIX_SPAWN is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_POSIX_SPAWNP != 1
#error "HAVE_POSIX_SPAWNP is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PREAD != 1
#error "HAVE_PREAD is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PREADV != 1
#error "HAVE_PREADV is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PREADV2 != 0
#error "HAVE_PREADV2 is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PROCESS_H != 0
#error "HAVE_PROCESS_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PTSNAME != 1
#error "HAVE_PTSNAME is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PTSNAME_R != 1
#error "HAVE_PTSNAME_R is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PTY_H != 1
#error "HAVE_PTY_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PWRITE != 1
#error "HAVE_PWRITE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PWRITEV != 1
#error "HAVE_PWRITEV is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_PWRITEV2 != 0
#error "HAVE_PWRITEV2 is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_READLINK != 1
#error "HAVE_READLINK is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_READLINKAT != 1
#error "HAVE_READLINKAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_READV != 1
#error "HAVE_READV is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_RENAMEAT != 1
#error "HAVE_RENAMEAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_RTPSPAWN != 0
#error "HAVE_RTPSPAWN is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SCHED_GET_PRIORITY_MAX != 1
#error "HAVE_SCHED_GET_PRIORITY_MAX is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SCHED_H != 1
#error "HAVE_SCHED_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SCHED_RR_GET_INTERVAL != 1
#error "HAVE_SCHED_RR_GET_INTERVAL is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SCHED_SETAFFINITY != 1
#error "HAVE_SCHED_SETAFFINITY is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SCHED_SETPARAM != 1
#error "HAVE_SCHED_SETPARAM is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SCHED_SETSCHEDULER != 1
#error "HAVE_SCHED_SETSCHEDULER is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SENDFILE != 1
#error "HAVE_SENDFILE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETEGID != 1
#error "HAVE_SETEGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETEUID != 1
#error "HAVE_SETEUID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETGID != 1
#error "HAVE_SETGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETGROUPS != 1
#error "HAVE_SETGROUPS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETNS != 1
#error "HAVE_SETNS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETPGID != 1
#error "HAVE_SETPGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETPGRP != 1
#error "HAVE_SETPGRP is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETPRIORITY != 1
#error "HAVE_SETPRIORITY is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETREGID != 1
#error "HAVE_SETREGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETRESGID != 1
#error "HAVE_SETRESGID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETRESUID != 1
#error "HAVE_SETRESUID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETREUID != 1
#error "HAVE_SETREUID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETSID != 1
#error "HAVE_SETSID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SETUID != 1
#error "HAVE_SETUID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SIGNAL_H != 1
#error "HAVE_SIGNAL_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SPLICE != 1
#error "HAVE_SPLICE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STATVFS != 1
#error "HAVE_STATVFS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STAT_TV_NSEC != 1
#error "HAVE_STAT_TV_NSEC is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STAT_TV_NSEC2 != 0
#error "HAVE_STAT_TV_NSEC2 is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STROPTS_H != 0
#error "HAVE_STROPTS_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BIRTHTIME != 0
#error "HAVE_STRUCT_STAT_ST_BIRTHTIME is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BLKSIZE != 1
#error "HAVE_STRUCT_STAT_ST_BLKSIZE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_BLOCKS != 1
#error "HAVE_STRUCT_STAT_ST_BLOCKS is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_FLAGS != 0
#error "HAVE_STRUCT_STAT_ST_FLAGS is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_GEN != 0
#error "HAVE_STRUCT_STAT_ST_GEN is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_STRUCT_STAT_ST_RDEV != 1
#error "HAVE_STRUCT_STAT_ST_RDEV is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYMLINK != 1
#error "HAVE_SYMLINK is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYMLINKAT != 1
#error "HAVE_SYMLINKAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYNC != 1
#error "HAVE_SYNC is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYSCONF != 1
#error "HAVE_SYSCONF is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYSEXITS_H != 1
#error "HAVE_SYSEXITS_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYSTEM != 1
#error "HAVE_SYSTEM is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_DIR_H != 0
#error "HAVE_SYS_DIR_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_EVENTFD_H != 1
#error "HAVE_SYS_EVENTFD_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_IOCTL_H != 1
#error "HAVE_SYS_IOCTL_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_LOADAVG_H != 0
#error "HAVE_SYS_LOADAVG_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_LOCK_H != 0
#error "HAVE_SYS_LOCK_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_MEMFD_H != 0
#error "HAVE_SYS_MEMFD_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_MKDEV_H != 0
#error "HAVE_SYS_MKDEV_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_MMAN_H != 1
#error "HAVE_SYS_MMAN_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_NDIR_H != 0
#error "HAVE_SYS_NDIR_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_PARAM_H != 1
#error "HAVE_SYS_PARAM_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_PIDFD_H != 1
#error "HAVE_SYS_PIDFD_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_RESOURCE_H != 1
#error "HAVE_SYS_RESOURCE_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_SENDFILE_H != 1
#error "HAVE_SYS_SENDFILE_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_SOCKET_H != 1
#error "HAVE_SYS_SOCKET_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_STATVFS_H != 1
#error "HAVE_SYS_STATVFS_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_STAT_H != 1
#error "HAVE_SYS_STAT_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_SYSMACROS_H != 1
#error "HAVE_SYS_SYSMACROS_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_TIMERFD_H != 1
#error "HAVE_SYS_TIMERFD_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_TIMES_H != 1
#error "HAVE_SYS_TIMES_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_TIME_H != 1
#error "HAVE_SYS_TIME_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_TYPES_H != 1
#error "HAVE_SYS_TYPES_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_UIO_H != 1
#error "HAVE_SYS_UIO_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_UTSNAME_H != 1
#error "HAVE_SYS_UTSNAME_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_WAIT_H != 1
#error "HAVE_SYS_WAIT_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_SYS_XATTR_H != 1
#error "HAVE_SYS_XATTR_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_TCGETPGRP != 1
#error "HAVE_TCGETPGRP is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_TCSETPGRP != 1
#error "HAVE_TCSETPGRP is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_TERMIOS_H != 1
#error "HAVE_TERMIOS_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_TIMERFD_CREATE != 1
#error "HAVE_TIMERFD_CREATE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_TRUNCATE != 1
#error "HAVE_TRUNCATE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_TTYNAME_R != 1
#error "HAVE_TTYNAME_R is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UMASK != 1
#error "HAVE_UMASK is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UNAME != 1
#error "HAVE_UNAME is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UNISTD_H != 1
#error "HAVE_UNISTD_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UNLINKAT != 1
#error "HAVE_UNLINKAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UNLOCKPT != 1
#error "HAVE_UNLOCKPT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UNSHARE != 1
#error "HAVE_UNSHARE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UTIL_H != 0
#error "HAVE_UTIL_H is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UTIMENSAT != 1
#error "HAVE_UTIMENSAT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UTIMES != 1
#error "HAVE_UTIMES is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UTIME_H != 1
#error "HAVE_UTIME_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UTMP_H != 1
#error "HAVE_UTMP_H is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_UT_NAMESIZE != 1
#error "HAVE_UT_NAMESIZE is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_WAIT != 1
#error "HAVE_WAIT is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_WAIT3 != 1
#error "HAVE_WAIT3 is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_WAIT4 != 1
#error "HAVE_WAIT4 is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_WAITID != 1
#error "HAVE_WAITID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_WAITPID != 1
#error "HAVE_WAITPID is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE_WRITEV != 1
#error "HAVE_WRITEV is not 1 as posix_constants.linux.x86_64.jac records"
#endif
#if HAVE__GETPTY != 0
#error "HAVE__GETPTY is not 0 as posix_constants.linux.x86_64.jac records"
#endif
#endif
