/* Generated by scripts/jacpython/gen_layouts.jac; do not edit.
 * Every layout and constant jaclang/runtime/python/layouts.jac declares,
 * asserted against the configured CPython headers. build.sh compiles this
 * for every JacPython build, so a layout drift fails the build. */
#ifndef Py_BUILD_CORE
#define Py_BUILD_CORE 1
#endif
#include "Python.h"
#include "internal/pycore_long.h"
#include <stddef.h>

#define FIELD(type, field, offset, size) \
    _Static_assert(offsetof(type, field) == (offset), #type "." #field " offset"); \
    _Static_assert(sizeof(((type *)0)->field) == (size), #type "." #field " size")
#define KIND(type, field, class) \
    _Static_assert(__builtin_classify_type(((type *)0)->field) == (class), \
                   #type "." #field " kind")
#define SIGNED(type, field, is_signed) \
    _Static_assert(((__typeof__(((type *)0)->field))-1 < 0) == (is_signed), \
                   #type "." #field " signedness")
#define LAYOUT(type, size, align) \
    _Static_assert(sizeof(type) == (size), #type " size"); \
    _Static_assert(_Alignof(type) == (align), #type " alignment")
#define CONSTANT(expression, value) \
    _Static_assert((long long)(expression) == (value), #expression)

/* _object */
FIELD(struct _object, ob_refcnt_full, 0, 8);
KIND(struct _object, ob_refcnt_full, 1);
SIGNED(struct _object, ob_refcnt_full, 1);
FIELD(struct _object, ob_type, 8, 8);
KIND(struct _object, ob_type, 5);
LAYOUT(struct _object, 16, 8);

/* PyVarObject */
FIELD(PyVarObject, ob_base, 0, 16);
KIND(PyVarObject, ob_base, 12);
FIELD(PyVarObject, ob_size, 16, 8);
KIND(PyVarObject, ob_size, 1);
SIGNED(PyVarObject, ob_size, 1);
LAYOUT(PyVarObject, 24, 8);

/* PyNumberMethods */
FIELD(PyNumberMethods, nb_add, 0, 8);
KIND(PyNumberMethods, nb_add, 5);
FIELD(PyNumberMethods, nb_subtract, 8, 8);
KIND(PyNumberMethods, nb_subtract, 5);
FIELD(PyNumberMethods, nb_multiply, 16, 8);
KIND(PyNumberMethods, nb_multiply, 5);
FIELD(PyNumberMethods, nb_remainder, 24, 8);
KIND(PyNumberMethods, nb_remainder, 5);
FIELD(PyNumberMethods, nb_divmod, 32, 8);
KIND(PyNumberMethods, nb_divmod, 5);
FIELD(PyNumberMethods, nb_power, 40, 8);
KIND(PyNumberMethods, nb_power, 5);
FIELD(PyNumberMethods, nb_negative, 48, 8);
KIND(PyNumberMethods, nb_negative, 5);
FIELD(PyNumberMethods, nb_positive, 56, 8);
KIND(PyNumberMethods, nb_positive, 5);
FIELD(PyNumberMethods, nb_absolute, 64, 8);
KIND(PyNumberMethods, nb_absolute, 5);
FIELD(PyNumberMethods, nb_bool, 72, 8);
KIND(PyNumberMethods, nb_bool, 5);
FIELD(PyNumberMethods, nb_invert, 80, 8);
KIND(PyNumberMethods, nb_invert, 5);
FIELD(PyNumberMethods, nb_lshift, 88, 8);
KIND(PyNumberMethods, nb_lshift, 5);
FIELD(PyNumberMethods, nb_rshift, 96, 8);
KIND(PyNumberMethods, nb_rshift, 5);
FIELD(PyNumberMethods, nb_and, 104, 8);
KIND(PyNumberMethods, nb_and, 5);
FIELD(PyNumberMethods, nb_xor, 112, 8);
KIND(PyNumberMethods, nb_xor, 5);
FIELD(PyNumberMethods, nb_or, 120, 8);
KIND(PyNumberMethods, nb_or, 5);
FIELD(PyNumberMethods, nb_int, 128, 8);
KIND(PyNumberMethods, nb_int, 5);
FIELD(PyNumberMethods, nb_reserved, 136, 8);
KIND(PyNumberMethods, nb_reserved, 5);
FIELD(PyNumberMethods, nb_float, 144, 8);
KIND(PyNumberMethods, nb_float, 5);
FIELD(PyNumberMethods, nb_inplace_add, 152, 8);
KIND(PyNumberMethods, nb_inplace_add, 5);
FIELD(PyNumberMethods, nb_inplace_subtract, 160, 8);
KIND(PyNumberMethods, nb_inplace_subtract, 5);
FIELD(PyNumberMethods, nb_inplace_multiply, 168, 8);
KIND(PyNumberMethods, nb_inplace_multiply, 5);
FIELD(PyNumberMethods, nb_inplace_remainder, 176, 8);
KIND(PyNumberMethods, nb_inplace_remainder, 5);
FIELD(PyNumberMethods, nb_inplace_power, 184, 8);
KIND(PyNumberMethods, nb_inplace_power, 5);
FIELD(PyNumberMethods, nb_inplace_lshift, 192, 8);
KIND(PyNumberMethods, nb_inplace_lshift, 5);
FIELD(PyNumberMethods, nb_inplace_rshift, 200, 8);
KIND(PyNumberMethods, nb_inplace_rshift, 5);
FIELD(PyNumberMethods, nb_inplace_and, 208, 8);
KIND(PyNumberMethods, nb_inplace_and, 5);
FIELD(PyNumberMethods, nb_inplace_xor, 216, 8);
KIND(PyNumberMethods, nb_inplace_xor, 5);
FIELD(PyNumberMethods, nb_inplace_or, 224, 8);
KIND(PyNumberMethods, nb_inplace_or, 5);
FIELD(PyNumberMethods, nb_floor_divide, 232, 8);
KIND(PyNumberMethods, nb_floor_divide, 5);
FIELD(PyNumberMethods, nb_true_divide, 240, 8);
KIND(PyNumberMethods, nb_true_divide, 5);
FIELD(PyNumberMethods, nb_inplace_floor_divide, 248, 8);
KIND(PyNumberMethods, nb_inplace_floor_divide, 5);
FIELD(PyNumberMethods, nb_inplace_true_divide, 256, 8);
KIND(PyNumberMethods, nb_inplace_true_divide, 5);
FIELD(PyNumberMethods, nb_index, 264, 8);
KIND(PyNumberMethods, nb_index, 5);
FIELD(PyNumberMethods, nb_matrix_multiply, 272, 8);
KIND(PyNumberMethods, nb_matrix_multiply, 5);
FIELD(PyNumberMethods, nb_inplace_matrix_multiply, 280, 8);
KIND(PyNumberMethods, nb_inplace_matrix_multiply, 5);
LAYOUT(PyNumberMethods, 288, 8);

/* PyTypeObject */
FIELD(struct _typeobject, ob_base, 0, 24);
KIND(struct _typeobject, ob_base, 12);
FIELD(struct _typeobject, tp_name, 24, 8);
KIND(struct _typeobject, tp_name, 5);
FIELD(struct _typeobject, tp_basicsize, 32, 8);
KIND(struct _typeobject, tp_basicsize, 1);
SIGNED(struct _typeobject, tp_basicsize, 1);
FIELD(struct _typeobject, tp_itemsize, 40, 8);
KIND(struct _typeobject, tp_itemsize, 1);
SIGNED(struct _typeobject, tp_itemsize, 1);
FIELD(struct _typeobject, tp_dealloc, 48, 8);
KIND(struct _typeobject, tp_dealloc, 5);
FIELD(struct _typeobject, tp_vectorcall_offset, 56, 8);
KIND(struct _typeobject, tp_vectorcall_offset, 1);
SIGNED(struct _typeobject, tp_vectorcall_offset, 1);
FIELD(struct _typeobject, tp_getattr, 64, 8);
KIND(struct _typeobject, tp_getattr, 5);
FIELD(struct _typeobject, tp_setattr, 72, 8);
KIND(struct _typeobject, tp_setattr, 5);
FIELD(struct _typeobject, tp_as_async, 80, 8);
KIND(struct _typeobject, tp_as_async, 5);
FIELD(struct _typeobject, tp_repr, 88, 8);
KIND(struct _typeobject, tp_repr, 5);
FIELD(struct _typeobject, tp_as_number, 96, 8);
KIND(struct _typeobject, tp_as_number, 5);
FIELD(struct _typeobject, tp_as_sequence, 104, 8);
KIND(struct _typeobject, tp_as_sequence, 5);
FIELD(struct _typeobject, tp_as_mapping, 112, 8);
KIND(struct _typeobject, tp_as_mapping, 5);
FIELD(struct _typeobject, tp_hash, 120, 8);
KIND(struct _typeobject, tp_hash, 5);
FIELD(struct _typeobject, tp_call, 128, 8);
KIND(struct _typeobject, tp_call, 5);
FIELD(struct _typeobject, tp_str, 136, 8);
KIND(struct _typeobject, tp_str, 5);
FIELD(struct _typeobject, tp_getattro, 144, 8);
KIND(struct _typeobject, tp_getattro, 5);
FIELD(struct _typeobject, tp_setattro, 152, 8);
KIND(struct _typeobject, tp_setattro, 5);
FIELD(struct _typeobject, tp_as_buffer, 160, 8);
KIND(struct _typeobject, tp_as_buffer, 5);
FIELD(struct _typeobject, tp_flags, 168, 8);
KIND(struct _typeobject, tp_flags, 1);
SIGNED(struct _typeobject, tp_flags, 0);
FIELD(struct _typeobject, tp_doc, 176, 8);
KIND(struct _typeobject, tp_doc, 5);
FIELD(struct _typeobject, tp_traverse, 184, 8);
KIND(struct _typeobject, tp_traverse, 5);
FIELD(struct _typeobject, tp_clear, 192, 8);
KIND(struct _typeobject, tp_clear, 5);
FIELD(struct _typeobject, tp_richcompare, 200, 8);
KIND(struct _typeobject, tp_richcompare, 5);
FIELD(struct _typeobject, tp_weaklistoffset, 208, 8);
KIND(struct _typeobject, tp_weaklistoffset, 1);
SIGNED(struct _typeobject, tp_weaklistoffset, 1);
FIELD(struct _typeobject, tp_iter, 216, 8);
KIND(struct _typeobject, tp_iter, 5);
FIELD(struct _typeobject, tp_iternext, 224, 8);
KIND(struct _typeobject, tp_iternext, 5);
FIELD(struct _typeobject, tp_methods, 232, 8);
KIND(struct _typeobject, tp_methods, 5);
FIELD(struct _typeobject, tp_members, 240, 8);
KIND(struct _typeobject, tp_members, 5);
FIELD(struct _typeobject, tp_getset, 248, 8);
KIND(struct _typeobject, tp_getset, 5);
FIELD(struct _typeobject, tp_base, 256, 8);
KIND(struct _typeobject, tp_base, 5);
FIELD(struct _typeobject, tp_dict, 264, 8);
KIND(struct _typeobject, tp_dict, 5);
FIELD(struct _typeobject, tp_descr_get, 272, 8);
KIND(struct _typeobject, tp_descr_get, 5);
FIELD(struct _typeobject, tp_descr_set, 280, 8);
KIND(struct _typeobject, tp_descr_set, 5);
FIELD(struct _typeobject, tp_dictoffset, 288, 8);
KIND(struct _typeobject, tp_dictoffset, 1);
SIGNED(struct _typeobject, tp_dictoffset, 1);
FIELD(struct _typeobject, tp_init, 296, 8);
KIND(struct _typeobject, tp_init, 5);
FIELD(struct _typeobject, tp_alloc, 304, 8);
KIND(struct _typeobject, tp_alloc, 5);
FIELD(struct _typeobject, tp_new, 312, 8);
KIND(struct _typeobject, tp_new, 5);
FIELD(struct _typeobject, tp_free, 320, 8);
KIND(struct _typeobject, tp_free, 5);
FIELD(struct _typeobject, tp_is_gc, 328, 8);
KIND(struct _typeobject, tp_is_gc, 5);
FIELD(struct _typeobject, tp_bases, 336, 8);
KIND(struct _typeobject, tp_bases, 5);
FIELD(struct _typeobject, tp_mro, 344, 8);
KIND(struct _typeobject, tp_mro, 5);
FIELD(struct _typeobject, tp_cache, 352, 8);
KIND(struct _typeobject, tp_cache, 5);
FIELD(struct _typeobject, tp_subclasses, 360, 8);
KIND(struct _typeobject, tp_subclasses, 5);
FIELD(struct _typeobject, tp_weaklist, 368, 8);
KIND(struct _typeobject, tp_weaklist, 5);
FIELD(struct _typeobject, tp_del, 376, 8);
KIND(struct _typeobject, tp_del, 5);
FIELD(struct _typeobject, tp_version_tag, 384, 4);
KIND(struct _typeobject, tp_version_tag, 1);
SIGNED(struct _typeobject, tp_version_tag, 0);
FIELD(struct _typeobject, tp_finalize, 392, 8);
KIND(struct _typeobject, tp_finalize, 5);
FIELD(struct _typeobject, tp_vectorcall, 400, 8);
KIND(struct _typeobject, tp_vectorcall, 5);
FIELD(struct _typeobject, tp_watched, 408, 1);
KIND(struct _typeobject, tp_watched, 1);
SIGNED(struct _typeobject, tp_watched, 0);
FIELD(struct _typeobject, tp_versions_used, 410, 2);
KIND(struct _typeobject, tp_versions_used, 1);
SIGNED(struct _typeobject, tp_versions_used, 0);
LAYOUT(struct _typeobject, 416, 8);

/* _PyLongValue */
FIELD(_PyLongValue, lv_tag, 0, 8);
KIND(_PyLongValue, lv_tag, 1);
SIGNED(_PyLongValue, lv_tag, 0);
FIELD(_PyLongValue, ob_digit, 8, 4);
KIND(_PyLongValue, ob_digit[0], 1);
SIGNED(_PyLongValue, ob_digit[0], 0);
LAYOUT(_PyLongValue, 16, 8);

/* PyLongObject */
FIELD(struct _longobject, ob_base, 0, 16);
KIND(struct _longobject, ob_base, 12);
FIELD(struct _longobject, long_value, 16, 16);
KIND(struct _longobject, long_value, 12);
LAYOUT(struct _longobject, 32, 8);

/* PyTupleObject */
FIELD(PyTupleObject, ob_base, 0, 24);
KIND(PyTupleObject, ob_base, 12);
FIELD(PyTupleObject, ob_hash, 24, 8);
KIND(PyTupleObject, ob_hash, 1);
SIGNED(PyTupleObject, ob_hash, 1);
FIELD(PyTupleObject, ob_item, 32, 8);
KIND(PyTupleObject, ob_item[0], 5);
LAYOUT(PyTupleObject, 40, 8);

CONSTANT(_Py_STATIC_IMMORTAL_INITIAL_REFCNT, 1407378104778752LL);
CONSTANT(Py_TPFLAGS_DEFAULT, 0LL);
CONSTANT(Py_TPFLAGS_TUPLE_SUBCLASS, 67108864LL);
CONSTANT(_PyLong_FALSE_TAG, 1LL);
CONSTANT(_PyLong_TRUE_TAG, 8LL);
CONSTANT(offsetof(struct _longobject, long_value.ob_digit), 24LL);
CONSTANT(sizeof(digit), 4LL);
