/* Generated by scripts/jacpython/gen_layouts.jac; do not edit.
 * Every layout and constant jaclang/runtime/python/layouts.jac declares,
 * asserted against the configured CPython headers. build.sh compiles this
 * for every JacPython build, so a layout drift fails the build. */
#ifndef Py_BUILD_CORE
#define Py_BUILD_CORE 1
#endif
#include "Python.h"
#include "internal/pycore_long.h"
#include "internal/pycore_time.h"
#define _PY_DATETIME_IMPL 1
#include "datetime.h"
#include <stddef.h>

#define FIELD(type, field, offset, size) \
    _Static_assert(offsetof(type, field) == (offset), #type "." #field " offset"); \
    _Static_assert(sizeof(((type *)0)->field) == (size), #type "." #field " size")
#define KIND(type, field, class) \
    _Static_assert(__builtin_classify_type(((type *)0)->field) == (class), \
                   #type "." #field " kind")
#define SIGNED(type, field, is_signed) \
    _Static_assert(((__typeof__(((type *)0)->field))-1 < 0) == (is_signed), \
                   #type "." #field " signedness")
#define LAYOUT(type, size, align) \
    _Static_assert(sizeof(type) == (size), #type " size"); \
    _Static_assert(_Alignof(type) == (align), #type " alignment")
#define CONSTANT(expression, value) \
    _Static_assert((long long)(expression) == (value), #expression)

/* _object */
FIELD(struct _object, ob_refcnt_full, 0, 8);
KIND(struct _object, ob_refcnt_full, 1);
SIGNED(struct _object, ob_refcnt_full, 1);
FIELD(struct _object, ob_type, 8, 8);
KIND(struct _object, ob_type, 5);
LAYOUT(struct _object, 16, 8);

/* PyVarObject */
FIELD(PyVarObject, ob_base, 0, 16);
KIND(PyVarObject, ob_base, 12);
FIELD(PyVarObject, ob_size, 16, 8);
KIND(PyVarObject, ob_size, 1);
SIGNED(PyVarObject, ob_size, 1);
LAYOUT(PyVarObject, 24, 8);

/* PyNumberMethods */
FIELD(PyNumberMethods, nb_add, 0, 8);
KIND(PyNumberMethods, nb_add, 5);
FIELD(PyNumberMethods, nb_subtract, 8, 8);
KIND(PyNumberMethods, nb_subtract, 5);
FIELD(PyNumberMethods, nb_multiply, 16, 8);
KIND(PyNumberMethods, nb_multiply, 5);
FIELD(PyNumberMethods, nb_remainder, 24, 8);
KIND(PyNumberMethods, nb_remainder, 5);
FIELD(PyNumberMethods, nb_divmod, 32, 8);
KIND(PyNumberMethods, nb_divmod, 5);
FIELD(PyNumberMethods, nb_power, 40, 8);
KIND(PyNumberMethods, nb_power, 5);
FIELD(PyNumberMethods, nb_negative, 48, 8);
KIND(PyNumberMethods, nb_negative, 5);
FIELD(PyNumberMethods, nb_positive, 56, 8);
KIND(PyNumberMethods, nb_positive, 5);
FIELD(PyNumberMethods, nb_absolute, 64, 8);
KIND(PyNumberMethods, nb_absolute, 5);
FIELD(PyNumberMethods, nb_bool, 72, 8);
KIND(PyNumberMethods, nb_bool, 5);
FIELD(PyNumberMethods, nb_invert, 80, 8);
KIND(PyNumberMethods, nb_invert, 5);
FIELD(PyNumberMethods, nb_lshift, 88, 8);
KIND(PyNumberMethods, nb_lshift, 5);
FIELD(PyNumberMethods, nb_rshift, 96, 8);
KIND(PyNumberMethods, nb_rshift, 5);
FIELD(PyNumberMethods, nb_and, 104, 8);
KIND(PyNumberMethods, nb_and, 5);
FIELD(PyNumberMethods, nb_xor, 112, 8);
KIND(PyNumberMethods, nb_xor, 5);
FIELD(PyNumberMethods, nb_or, 120, 8);
KIND(PyNumberMethods, nb_or, 5);
FIELD(PyNumberMethods, nb_int, 128, 8);
KIND(PyNumberMethods, nb_int, 5);
FIELD(PyNumberMethods, nb_reserved, 136, 8);
KIND(PyNumberMethods, nb_reserved, 5);
FIELD(PyNumberMethods, nb_float, 144, 8);
KIND(PyNumberMethods, nb_float, 5);
FIELD(PyNumberMethods, nb_inplace_add, 152, 8);
KIND(PyNumberMethods, nb_inplace_add, 5);
FIELD(PyNumberMethods, nb_inplace_subtract, 160, 8);
KIND(PyNumberMethods, nb_inplace_subtract, 5);
FIELD(PyNumberMethods, nb_inplace_multiply, 168, 8);
KIND(PyNumberMethods, nb_inplace_multiply, 5);
FIELD(PyNumberMethods, nb_inplace_remainder, 176, 8);
KIND(PyNumberMethods, nb_inplace_remainder, 5);
FIELD(PyNumberMethods, nb_inplace_power, 184, 8);
KIND(PyNumberMethods, nb_inplace_power, 5);
FIELD(PyNumberMethods, nb_inplace_lshift, 192, 8);
KIND(PyNumberMethods, nb_inplace_lshift, 5);
FIELD(PyNumberMethods, nb_inplace_rshift, 200, 8);
KIND(PyNumberMethods, nb_inplace_rshift, 5);
FIELD(PyNumberMethods, nb_inplace_and, 208, 8);
KIND(PyNumberMethods, nb_inplace_and, 5);
FIELD(PyNumberMethods, nb_inplace_xor, 216, 8);
KIND(PyNumberMethods, nb_inplace_xor, 5);
FIELD(PyNumberMethods, nb_inplace_or, 224, 8);
KIND(PyNumberMethods, nb_inplace_or, 5);
FIELD(PyNumberMethods, nb_floor_divide, 232, 8);
KIND(PyNumberMethods, nb_floor_divide, 5);
FIELD(PyNumberMethods, nb_true_divide, 240, 8);
KIND(PyNumberMethods, nb_true_divide, 5);
FIELD(PyNumberMethods, nb_inplace_floor_divide, 248, 8);
KIND(PyNumberMethods, nb_inplace_floor_divide, 5);
FIELD(PyNumberMethods, nb_inplace_true_divide, 256, 8);
KIND(PyNumberMethods, nb_inplace_true_divide, 5);
FIELD(PyNumberMethods, nb_index, 264, 8);
KIND(PyNumberMethods, nb_index, 5);
FIELD(PyNumberMethods, nb_matrix_multiply, 272, 8);
KIND(PyNumberMethods, nb_matrix_multiply, 5);
FIELD(PyNumberMethods, nb_inplace_matrix_multiply, 280, 8);
KIND(PyNumberMethods, nb_inplace_matrix_multiply, 5);
LAYOUT(PyNumberMethods, 288, 8);

/* PyTypeObject */
FIELD(struct _typeobject, ob_base, 0, 24);
KIND(struct _typeobject, ob_base, 12);
FIELD(struct _typeobject, tp_name, 24, 8);
KIND(struct _typeobject, tp_name, 5);
FIELD(struct _typeobject, tp_basicsize, 32, 8);
KIND(struct _typeobject, tp_basicsize, 1);
SIGNED(struct _typeobject, tp_basicsize, 1);
FIELD(struct _typeobject, tp_itemsize, 40, 8);
KIND(struct _typeobject, tp_itemsize, 1);
SIGNED(struct _typeobject, tp_itemsize, 1);
FIELD(struct _typeobject, tp_dealloc, 48, 8);
KIND(struct _typeobject, tp_dealloc, 5);
FIELD(struct _typeobject, tp_vectorcall_offset, 56, 8);
KIND(struct _typeobject, tp_vectorcall_offset, 1);
SIGNED(struct _typeobject, tp_vectorcall_offset, 1);
FIELD(struct _typeobject, tp_getattr, 64, 8);
KIND(struct _typeobject, tp_getattr, 5);
FIELD(struct _typeobject, tp_setattr, 72, 8);
KIND(struct _typeobject, tp_setattr, 5);
FIELD(struct _typeobject, tp_as_async, 80, 8);
KIND(struct _typeobject, tp_as_async, 5);
FIELD(struct _typeobject, tp_repr, 88, 8);
KIND(struct _typeobject, tp_repr, 5);
FIELD(struct _typeobject, tp_as_number, 96, 8);
KIND(struct _typeobject, tp_as_number, 5);
FIELD(struct _typeobject, tp_as_sequence, 104, 8);
KIND(struct _typeobject, tp_as_sequence, 5);
FIELD(struct _typeobject, tp_as_mapping, 112, 8);
KIND(struct _typeobject, tp_as_mapping, 5);
FIELD(struct _typeobject, tp_hash, 120, 8);
KIND(struct _typeobject, tp_hash, 5);
FIELD(struct _typeobject, tp_call, 128, 8);
KIND(struct _typeobject, tp_call, 5);
FIELD(struct _typeobject, tp_str, 136, 8);
KIND(struct _typeobject, tp_str, 5);
FIELD(struct _typeobject, tp_getattro, 144, 8);
KIND(struct _typeobject, tp_getattro, 5);
FIELD(struct _typeobject, tp_setattro, 152, 8);
KIND(struct _typeobject, tp_setattro, 5);
FIELD(struct _typeobject, tp_as_buffer, 160, 8);
KIND(struct _typeobject, tp_as_buffer, 5);
FIELD(struct _typeobject, tp_flags, 168, 8);
KIND(struct _typeobject, tp_flags, 1);
SIGNED(struct _typeobject, tp_flags, 0);
FIELD(struct _typeobject, tp_doc, 176, 8);
KIND(struct _typeobject, tp_doc, 5);
FIELD(struct _typeobject, tp_traverse, 184, 8);
KIND(struct _typeobject, tp_traverse, 5);
FIELD(struct _typeobject, tp_clear, 192, 8);
KIND(struct _typeobject, tp_clear, 5);
FIELD(struct _typeobject, tp_richcompare, 200, 8);
KIND(struct _typeobject, tp_richcompare, 5);
FIELD(struct _typeobject, tp_weaklistoffset, 208, 8);
KIND(struct _typeobject, tp_weaklistoffset, 1);
SIGNED(struct _typeobject, tp_weaklistoffset, 1);
FIELD(struct _typeobject, tp_iter, 216, 8);
KIND(struct _typeobject, tp_iter, 5);
FIELD(struct _typeobject, tp_iternext, 224, 8);
KIND(struct _typeobject, tp_iternext, 5);
FIELD(struct _typeobject, tp_methods, 232, 8);
KIND(struct _typeobject, tp_methods, 5);
FIELD(struct _typeobject, tp_members, 240, 8);
KIND(struct _typeobject, tp_members, 5);
FIELD(struct _typeobject, tp_getset, 248, 8);
KIND(struct _typeobject, tp_getset, 5);
FIELD(struct _typeobject, tp_base, 256, 8);
KIND(struct _typeobject, tp_base, 5);
FIELD(struct _typeobject, tp_dict, 264, 8);
KIND(struct _typeobject, tp_dict, 5);
FIELD(struct _typeobject, tp_descr_get, 272, 8);
KIND(struct _typeobject, tp_descr_get, 5);
FIELD(struct _typeobject, tp_descr_set, 280, 8);
KIND(struct _typeobject, tp_descr_set, 5);
FIELD(struct _typeobject, tp_dictoffset, 288, 8);
KIND(struct _typeobject, tp_dictoffset, 1);
SIGNED(struct _typeobject, tp_dictoffset, 1);
FIELD(struct _typeobject, tp_init, 296, 8);
KIND(struct _typeobject, tp_init, 5);
FIELD(struct _typeobject, tp_alloc, 304, 8);
KIND(struct _typeobject, tp_alloc, 5);
FIELD(struct _typeobject, tp_new, 312, 8);
KIND(struct _typeobject, tp_new, 5);
FIELD(struct _typeobject, tp_free, 320, 8);
KIND(struct _typeobject, tp_free, 5);
FIELD(struct _typeobject, tp_is_gc, 328, 8);
KIND(struct _typeobject, tp_is_gc, 5);
FIELD(struct _typeobject, tp_bases, 336, 8);
KIND(struct _typeobject, tp_bases, 5);
FIELD(struct _typeobject, tp_mro, 344, 8);
KIND(struct _typeobject, tp_mro, 5);
FIELD(struct _typeobject, tp_cache, 352, 8);
KIND(struct _typeobject, tp_cache, 5);
FIELD(struct _typeobject, tp_subclasses, 360, 8);
KIND(struct _typeobject, tp_subclasses, 5);
FIELD(struct _typeobject, tp_weaklist, 368, 8);
KIND(struct _typeobject, tp_weaklist, 5);
FIELD(struct _typeobject, tp_del, 376, 8);
KIND(struct _typeobject, tp_del, 5);
FIELD(struct _typeobject, tp_version_tag, 384, 4);
KIND(struct _typeobject, tp_version_tag, 1);
SIGNED(struct _typeobject, tp_version_tag, 0);
FIELD(struct _typeobject, tp_finalize, 392, 8);
KIND(struct _typeobject, tp_finalize, 5);
FIELD(struct _typeobject, tp_vectorcall, 400, 8);
KIND(struct _typeobject, tp_vectorcall, 5);
FIELD(struct _typeobject, tp_watched, 408, 1);
KIND(struct _typeobject, tp_watched, 1);
SIGNED(struct _typeobject, tp_watched, 0);
FIELD(struct _typeobject, tp_versions_used, 410, 2);
KIND(struct _typeobject, tp_versions_used, 1);
SIGNED(struct _typeobject, tp_versions_used, 0);
LAYOUT(struct _typeobject, 416, 8);

/* _PyLongValue */
FIELD(_PyLongValue, lv_tag, 0, 8);
KIND(_PyLongValue, lv_tag, 1);
SIGNED(_PyLongValue, lv_tag, 0);
FIELD(_PyLongValue, ob_digit, 8, 4);
KIND(_PyLongValue, ob_digit[0], 1);
SIGNED(_PyLongValue, ob_digit[0], 0);
LAYOUT(_PyLongValue, 16, 8);

/* PyLongObject */
FIELD(struct _longobject, ob_base, 0, 16);
KIND(struct _longobject, ob_base, 12);
FIELD(struct _longobject, long_value, 16, 16);
KIND(struct _longobject, long_value, 12);
LAYOUT(struct _longobject, 32, 8);

/* PyTupleObject */
FIELD(PyTupleObject, ob_base, 0, 24);
KIND(PyTupleObject, ob_base, 12);
FIELD(PyTupleObject, ob_hash, 24, 8);
KIND(PyTupleObject, ob_hash, 1);
SIGNED(PyTupleObject, ob_hash, 1);
FIELD(PyTupleObject, ob_item, 32, 8);
KIND(PyTupleObject, ob_item[0], 5);
LAYOUT(PyTupleObject, 40, 8);

/* PyStatus */
FIELD(PyStatus, _type, 0, 4);
KIND(PyStatus, _type, 1);
SIGNED(PyStatus, _type, 0);
FIELD(PyStatus, func, 8, 8);
KIND(PyStatus, func, 5);
FIELD(PyStatus, err_msg, 16, 8);
KIND(PyStatus, err_msg, 5);
FIELD(PyStatus, exitcode, 24, 4);
KIND(PyStatus, exitcode, 1);
SIGNED(PyStatus, exitcode, 1);
LAYOUT(PyStatus, 32, 8);

/* PyGetSetDef */
FIELD(struct PyGetSetDef, name, 0, 8);
KIND(struct PyGetSetDef, name, 5);
FIELD(struct PyGetSetDef, get, 8, 8);
KIND(struct PyGetSetDef, get, 5);
FIELD(struct PyGetSetDef, set, 16, 8);
KIND(struct PyGetSetDef, set, 5);
FIELD(struct PyGetSetDef, doc, 24, 8);
KIND(struct PyGetSetDef, doc, 5);
FIELD(struct PyGetSetDef, closure, 32, 8);
KIND(struct PyGetSetDef, closure, 5);
LAYOUT(struct PyGetSetDef, 40, 8);

/* PyDateTime_Delta */
FIELD(PyDateTime_Delta, ob_base, 0, 16);
KIND(PyDateTime_Delta, ob_base, 12);
FIELD(PyDateTime_Delta, hashcode, 16, 8);
KIND(PyDateTime_Delta, hashcode, 1);
SIGNED(PyDateTime_Delta, hashcode, 1);
FIELD(PyDateTime_Delta, days, 24, 4);
KIND(PyDateTime_Delta, days, 1);
SIGNED(PyDateTime_Delta, days, 1);
FIELD(PyDateTime_Delta, seconds, 28, 4);
KIND(PyDateTime_Delta, seconds, 1);
SIGNED(PyDateTime_Delta, seconds, 1);
FIELD(PyDateTime_Delta, microseconds, 32, 4);
KIND(PyDateTime_Delta, microseconds, 1);
SIGNED(PyDateTime_Delta, microseconds, 1);
LAYOUT(PyDateTime_Delta, 40, 8);

/* PyDateTime_TZInfo */
FIELD(PyDateTime_TZInfo, ob_base, 0, 16);
KIND(PyDateTime_TZInfo, ob_base, 12);
LAYOUT(PyDateTime_TZInfo, 16, 8);

/* _PyDateTime_BaseTZInfo */
FIELD(_PyDateTime_BaseTZInfo, ob_base, 0, 16);
KIND(_PyDateTime_BaseTZInfo, ob_base, 12);
FIELD(_PyDateTime_BaseTZInfo, hashcode, 16, 8);
KIND(_PyDateTime_BaseTZInfo, hashcode, 1);
SIGNED(_PyDateTime_BaseTZInfo, hashcode, 1);
FIELD(_PyDateTime_BaseTZInfo, hastzinfo, 24, 1);
KIND(_PyDateTime_BaseTZInfo, hastzinfo, 1);
SIGNED(_PyDateTime_BaseTZInfo, hastzinfo, 1);
LAYOUT(_PyDateTime_BaseTZInfo, 32, 8);

/* _PyDateTime_BaseTime */
FIELD(_PyDateTime_BaseTime, ob_base, 0, 16);
KIND(_PyDateTime_BaseTime, ob_base, 12);
FIELD(_PyDateTime_BaseTime, hashcode, 16, 8);
KIND(_PyDateTime_BaseTime, hashcode, 1);
SIGNED(_PyDateTime_BaseTime, hashcode, 1);
FIELD(_PyDateTime_BaseTime, hastzinfo, 24, 1);
KIND(_PyDateTime_BaseTime, hastzinfo, 1);
SIGNED(_PyDateTime_BaseTime, hastzinfo, 1);
FIELD(_PyDateTime_BaseTime, data[0], 25, 1);
KIND(_PyDateTime_BaseTime, data[0], 1);
SIGNED(_PyDateTime_BaseTime, data[0], 0);
FIELD(_PyDateTime_BaseTime, data[1], 26, 1);
KIND(_PyDateTime_BaseTime, data[1], 1);
SIGNED(_PyDateTime_BaseTime, data[1], 0);
FIELD(_PyDateTime_BaseTime, data[2], 27, 1);
KIND(_PyDateTime_BaseTime, data[2], 1);
SIGNED(_PyDateTime_BaseTime, data[2], 0);
FIELD(_PyDateTime_BaseTime, data[3], 28, 1);
KIND(_PyDateTime_BaseTime, data[3], 1);
SIGNED(_PyDateTime_BaseTime, data[3], 0);
FIELD(_PyDateTime_BaseTime, data[4], 29, 1);
KIND(_PyDateTime_BaseTime, data[4], 1);
SIGNED(_PyDateTime_BaseTime, data[4], 0);
FIELD(_PyDateTime_BaseTime, data[5], 30, 1);
KIND(_PyDateTime_BaseTime, data[5], 1);
SIGNED(_PyDateTime_BaseTime, data[5], 0);
LAYOUT(_PyDateTime_BaseTime, 32, 8);

/* PyDateTime_Time */
FIELD(PyDateTime_Time, ob_base, 0, 16);
KIND(PyDateTime_Time, ob_base, 12);
FIELD(PyDateTime_Time, hashcode, 16, 8);
KIND(PyDateTime_Time, hashcode, 1);
SIGNED(PyDateTime_Time, hashcode, 1);
FIELD(PyDateTime_Time, hastzinfo, 24, 1);
KIND(PyDateTime_Time, hastzinfo, 1);
SIGNED(PyDateTime_Time, hastzinfo, 1);
FIELD(PyDateTime_Time, data[0], 25, 1);
KIND(PyDateTime_Time, data[0], 1);
SIGNED(PyDateTime_Time, data[0], 0);
FIELD(PyDateTime_Time, data[1], 26, 1);
KIND(PyDateTime_Time, data[1], 1);
SIGNED(PyDateTime_Time, data[1], 0);
FIELD(PyDateTime_Time, data[2], 27, 1);
KIND(PyDateTime_Time, data[2], 1);
SIGNED(PyDateTime_Time, data[2], 0);
FIELD(PyDateTime_Time, data[3], 28, 1);
KIND(PyDateTime_Time, data[3], 1);
SIGNED(PyDateTime_Time, data[3], 0);
FIELD(PyDateTime_Time, data[4], 29, 1);
KIND(PyDateTime_Time, data[4], 1);
SIGNED(PyDateTime_Time, data[4], 0);
FIELD(PyDateTime_Time, data[5], 30, 1);
KIND(PyDateTime_Time, data[5], 1);
SIGNED(PyDateTime_Time, data[5], 0);
FIELD(PyDateTime_Time, fold, 31, 1);
KIND(PyDateTime_Time, fold, 1);
SIGNED(PyDateTime_Time, fold, 0);
FIELD(PyDateTime_Time, tzinfo, 32, 8);
KIND(PyDateTime_Time, tzinfo, 5);
LAYOUT(PyDateTime_Time, 40, 8);

/* PyDateTime_Date */
FIELD(PyDateTime_Date, ob_base, 0, 16);
KIND(PyDateTime_Date, ob_base, 12);
FIELD(PyDateTime_Date, hashcode, 16, 8);
KIND(PyDateTime_Date, hashcode, 1);
SIGNED(PyDateTime_Date, hashcode, 1);
FIELD(PyDateTime_Date, hastzinfo, 24, 1);
KIND(PyDateTime_Date, hastzinfo, 1);
SIGNED(PyDateTime_Date, hastzinfo, 1);
FIELD(PyDateTime_Date, data[0], 25, 1);
KIND(PyDateTime_Date, data[0], 1);
SIGNED(PyDateTime_Date, data[0], 0);
FIELD(PyDateTime_Date, data[1], 26, 1);
KIND(PyDateTime_Date, data[1], 1);
SIGNED(PyDateTime_Date, data[1], 0);
FIELD(PyDateTime_Date, data[2], 27, 1);
KIND(PyDateTime_Date, data[2], 1);
SIGNED(PyDateTime_Date, data[2], 0);
FIELD(PyDateTime_Date, data[3], 28, 1);
KIND(PyDateTime_Date, data[3], 1);
SIGNED(PyDateTime_Date, data[3], 0);
LAYOUT(PyDateTime_Date, 32, 8);

/* _PyDateTime_BaseDateTime */
FIELD(_PyDateTime_BaseDateTime, ob_base, 0, 16);
KIND(_PyDateTime_BaseDateTime, ob_base, 12);
FIELD(_PyDateTime_BaseDateTime, hashcode, 16, 8);
KIND(_PyDateTime_BaseDateTime, hashcode, 1);
SIGNED(_PyDateTime_BaseDateTime, hashcode, 1);
FIELD(_PyDateTime_BaseDateTime, hastzinfo, 24, 1);
KIND(_PyDateTime_BaseDateTime, hastzinfo, 1);
SIGNED(_PyDateTime_BaseDateTime, hastzinfo, 1);
FIELD(_PyDateTime_BaseDateTime, data[0], 25, 1);
KIND(_PyDateTime_BaseDateTime, data[0], 1);
SIGNED(_PyDateTime_BaseDateTime, data[0], 0);
FIELD(_PyDateTime_BaseDateTime, data[1], 26, 1);
KIND(_PyDateTime_BaseDateTime, data[1], 1);
SIGNED(_PyDateTime_BaseDateTime, data[1], 0);
FIELD(_PyDateTime_BaseDateTime, data[2], 27, 1);
KIND(_PyDateTime_BaseDateTime, data[2], 1);
SIGNED(_PyDateTime_BaseDateTime, data[2], 0);
FIELD(_PyDateTime_BaseDateTime, data[3], 28, 1);
KIND(_PyDateTime_BaseDateTime, data[3], 1);
SIGNED(_PyDateTime_BaseDateTime, data[3], 0);
FIELD(_PyDateTime_BaseDateTime, data[4], 29, 1);
KIND(_PyDateTime_BaseDateTime, data[4], 1);
SIGNED(_PyDateTime_BaseDateTime, data[4], 0);
FIELD(_PyDateTime_BaseDateTime, data[5], 30, 1);
KIND(_PyDateTime_BaseDateTime, data[5], 1);
SIGNED(_PyDateTime_BaseDateTime, data[5], 0);
FIELD(_PyDateTime_BaseDateTime, data[6], 31, 1);
KIND(_PyDateTime_BaseDateTime, data[6], 1);
SIGNED(_PyDateTime_BaseDateTime, data[6], 0);
FIELD(_PyDateTime_BaseDateTime, data[7], 32, 1);
KIND(_PyDateTime_BaseDateTime, data[7], 1);
SIGNED(_PyDateTime_BaseDateTime, data[7], 0);
FIELD(_PyDateTime_BaseDateTime, data[8], 33, 1);
KIND(_PyDateTime_BaseDateTime, data[8], 1);
SIGNED(_PyDateTime_BaseDateTime, data[8], 0);
FIELD(_PyDateTime_BaseDateTime, data[9], 34, 1);
KIND(_PyDateTime_BaseDateTime, data[9], 1);
SIGNED(_PyDateTime_BaseDateTime, data[9], 0);
LAYOUT(_PyDateTime_BaseDateTime, 40, 8);

/* PyDateTime_DateTime */
FIELD(PyDateTime_DateTime, ob_base, 0, 16);
KIND(PyDateTime_DateTime, ob_base, 12);
FIELD(PyDateTime_DateTime, hashcode, 16, 8);
KIND(PyDateTime_DateTime, hashcode, 1);
SIGNED(PyDateTime_DateTime, hashcode, 1);
FIELD(PyDateTime_DateTime, hastzinfo, 24, 1);
KIND(PyDateTime_DateTime, hastzinfo, 1);
SIGNED(PyDateTime_DateTime, hastzinfo, 1);
FIELD(PyDateTime_DateTime, data[0], 25, 1);
KIND(PyDateTime_DateTime, data[0], 1);
SIGNED(PyDateTime_DateTime, data[0], 0);
FIELD(PyDateTime_DateTime, data[1], 26, 1);
KIND(PyDateTime_DateTime, data[1], 1);
SIGNED(PyDateTime_DateTime, data[1], 0);
FIELD(PyDateTime_DateTime, data[2], 27, 1);
KIND(PyDateTime_DateTime, data[2], 1);
SIGNED(PyDateTime_DateTime, data[2], 0);
FIELD(PyDateTime_DateTime, data[3], 28, 1);
KIND(PyDateTime_DateTime, data[3], 1);
SIGNED(PyDateTime_DateTime, data[3], 0);
FIELD(PyDateTime_DateTime, data[4], 29, 1);
KIND(PyDateTime_DateTime, data[4], 1);
SIGNED(PyDateTime_DateTime, data[4], 0);
FIELD(PyDateTime_DateTime, data[5], 30, 1);
KIND(PyDateTime_DateTime, data[5], 1);
SIGNED(PyDateTime_DateTime, data[5], 0);
FIELD(PyDateTime_DateTime, data[6], 31, 1);
KIND(PyDateTime_DateTime, data[6], 1);
SIGNED(PyDateTime_DateTime, data[6], 0);
FIELD(PyDateTime_DateTime, data[7], 32, 1);
KIND(PyDateTime_DateTime, data[7], 1);
SIGNED(PyDateTime_DateTime, data[7], 0);
FIELD(PyDateTime_DateTime, data[8], 33, 1);
KIND(PyDateTime_DateTime, data[8], 1);
SIGNED(PyDateTime_DateTime, data[8], 0);
FIELD(PyDateTime_DateTime, data[9], 34, 1);
KIND(PyDateTime_DateTime, data[9], 1);
SIGNED(PyDateTime_DateTime, data[9], 0);
FIELD(PyDateTime_DateTime, fold, 35, 1);
KIND(PyDateTime_DateTime, fold, 1);
SIGNED(PyDateTime_DateTime, fold, 0);
FIELD(PyDateTime_DateTime, tzinfo, 40, 8);
KIND(PyDateTime_DateTime, tzinfo, 5);
LAYOUT(PyDateTime_DateTime, 48, 8);

/* PyDateTime_CAPI */
FIELD(PyDateTime_CAPI, DateType, 0, 8);
KIND(PyDateTime_CAPI, DateType, 5);
FIELD(PyDateTime_CAPI, DateTimeType, 8, 8);
KIND(PyDateTime_CAPI, DateTimeType, 5);
FIELD(PyDateTime_CAPI, TimeType, 16, 8);
KIND(PyDateTime_CAPI, TimeType, 5);
FIELD(PyDateTime_CAPI, DeltaType, 24, 8);
KIND(PyDateTime_CAPI, DeltaType, 5);
FIELD(PyDateTime_CAPI, TZInfoType, 32, 8);
KIND(PyDateTime_CAPI, TZInfoType, 5);
FIELD(PyDateTime_CAPI, TimeZone_UTC, 40, 8);
KIND(PyDateTime_CAPI, TimeZone_UTC, 5);
FIELD(PyDateTime_CAPI, Date_FromDate, 48, 8);
KIND(PyDateTime_CAPI, Date_FromDate, 5);
FIELD(PyDateTime_CAPI, DateTime_FromDateAndTime, 56, 8);
KIND(PyDateTime_CAPI, DateTime_FromDateAndTime, 5);
FIELD(PyDateTime_CAPI, Time_FromTime, 64, 8);
KIND(PyDateTime_CAPI, Time_FromTime, 5);
FIELD(PyDateTime_CAPI, Delta_FromDelta, 72, 8);
KIND(PyDateTime_CAPI, Delta_FromDelta, 5);
FIELD(PyDateTime_CAPI, TimeZone_FromTimeZone, 80, 8);
KIND(PyDateTime_CAPI, TimeZone_FromTimeZone, 5);
FIELD(PyDateTime_CAPI, DateTime_FromTimestamp, 88, 8);
KIND(PyDateTime_CAPI, DateTime_FromTimestamp, 5);
FIELD(PyDateTime_CAPI, Date_FromTimestamp, 96, 8);
KIND(PyDateTime_CAPI, Date_FromTimestamp, 5);
FIELD(PyDateTime_CAPI, DateTime_FromDateAndTimeAndFold, 104, 8);
KIND(PyDateTime_CAPI, DateTime_FromDateAndTimeAndFold, 5);
FIELD(PyDateTime_CAPI, Time_FromTimeAndFold, 112, 8);
KIND(PyDateTime_CAPI, Time_FromTimeAndFold, 5);
LAYOUT(PyDateTime_CAPI, 120, 8);

CONSTANT(_Py_STATIC_IMMORTAL_INITIAL_REFCNT, 1407378104778752LL);
CONSTANT(Py_TPFLAGS_DEFAULT, 0LL);
CONSTANT(Py_TPFLAGS_TUPLE_SUBCLASS, 67108864LL);
CONSTANT(_PyLong_FALSE_TAG, 1LL);
CONSTANT(_PyLong_TRUE_TAG, 8LL);
CONSTANT(offsetof(struct _longobject, long_value.ob_digit), 24LL);
CONSTANT(sizeof(digit), 4LL);
CONSTANT(_PyStatus_TYPE_OK, 0LL);
CONSTANT(_PyStatus_TYPE_ERROR, 1LL);
CONSTANT(sizeof(Py_buffer), 80LL);
CONSTANT(sizeof(PyObject), 16LL);
CONSTANT(sizeof(PyTupleObject), 40LL);
CONSTANT(Py_TPFLAGS_BASETYPE, 1024LL);
CONSTANT(Py_TPFLAGS_HAVE_GC, 16384LL);
CONSTANT(Py_TPFLAGS_IMMUTABLETYPE, 256LL);
CONSTANT(METH_VARARGS, 1LL);
CONSTANT(METH_KEYWORDS, 2LL);
CONSTANT(METH_NOARGS, 4LL);
CONSTANT(METH_O, 8LL);
CONSTANT(METH_CLASS, 16LL);
CONSTANT(METH_STATIC, 32LL);
CONSTANT(Py_T_INT, 1LL);
CONSTANT(Py_READONLY, 1LL);
CONSTANT(Py_tp_dealloc, 52LL);
CONSTANT(Py_tp_doc, 56LL);
CONSTANT(Py_tp_getset, 73LL);
CONSTANT(Py_tp_methods, 64LL);
CONSTANT(Py_tp_new, 65LL);
CONSTANT(Py_tp_repr, 66LL);
CONSTANT(Py_tp_traverse, 71LL);
CONSTANT(sizeof(PyDateTime_Delta), 40LL);
CONSTANT(sizeof(PyDateTime_TZInfo), 16LL);
CONSTANT(sizeof(PyDateTime_Date), 32LL);
CONSTANT(sizeof(_PyDateTime_BaseTime), 32LL);
CONSTANT(sizeof(PyDateTime_Time), 40LL);
CONSTANT(sizeof(_PyDateTime_BaseDateTime), 40LL);
CONSTANT(sizeof(PyDateTime_DateTime), 48LL);
CONSTANT(offsetof(PyDateTime_Date, data), 25LL);
CONSTANT(offsetof(PyDateTime_Delta, days), 24LL);
CONSTANT(offsetof(PyDateTime_Delta, seconds), 28LL);
CONSTANT(offsetof(PyDateTime_Delta, microseconds), 32LL);
CONSTANT(Py_CONSTANT_ONE, 6LL);
CONSTANT(Py_CONSTANT_EMPTY_STR, 7LL);
CONSTANT(_PyTime_ROUND_FLOOR, 0LL);
CONSTANT(_PyTime_ROUND_HALF_EVEN, 2LL);
